// Ma Semaine — données de base : catalogue des ingrédients et des plats.
//
// Origine : reprises telles quelles depuis le Notion de Qassim (bases
// "🧺 Ingrédients" et "📖 Mes plats & repas"), voir CLAUDE.md § Données existantes.
// Les quantités par portion viennent de la base "🧾 Composition des plats"
// (déjà calculées là-bas en divisant la recette totale par son nombre de portions).
//
// Ce fichier ne contient QUE des données statiques (aucune fonction de calcul :
// ça, c'est le rôle de calculs.js, à l'étape suivante).

// --- Catalogue des ingrédients ---
// unite : l'unité dans laquelle le stock de cet ingrédient est compté.
// parCuillereACafe : pour les ingrédients dosés en cuillères dans les recettes,
//   la quantité (dans "unite") que représente 1 c. à café. null si non concerné.
//   1 c. à soupe = 3 c. à café (conversion utilisée par calculs.js).
export const ingredients = [
  {
    id: "paprika",
    nom: "Paprika",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 2.5,
  },
  {
    id: "banane",
    nom: "Banane",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "huile-d-olive",
    nom: "Huile d'olive",
    rayon: "Épicerie salée",
    unite: "ml",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "pois-chiches",
    nom: "Pois chiches",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "bouillon-de-volaille-halal",
    nom: "Bouillon de volaille halal",
    rayon: "Épicerie salée",
    unite: "cube",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pouch-skyr-15-g-de-proteines",
    nom: "Pouch skyr (≈ 15 g de protéines)",
    rayon: "Crèmerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "feta-de-brebis",
    nom: "Feta de brebis",
    rayon: "Crèmerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "epinards",
    nom: "Épinards",
    rayon: "Surgelés",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "tomates",
    nom: "Tomates",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "citron",
    nom: "Citron",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "dattes",
    nom: "Dattes",
    rayon: "Épicerie sucrée",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "ail",
    nom: "Ail",
    rayon: "Fruits et légumes",
    unite: "gousse",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "tomates-cerises",
    nom: "Tomates cerises",
    rayon: "Fruits et légumes",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "beurre-de-cacahuete-100-arachide",
    nom: "Beurre de cacahuète 100% arachide",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "roquette",
    nom: "Roquette",
    rayon: "Fruits et légumes",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "riz",
    nom: "Riz",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "graines-de-chia",
    nom: "Graines de chia",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 4,
  },
  {
    id: "patate-douce",
    nom: "Patate douce",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pates-spaghetti",
    nom: "Pâtes (spaghetti)",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "orge-perle",
    nom: "Orge perlé",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "blettes",
    nom: "Blettes",
    rayon: "Fruits et légumes",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "fruits-rouges",
    nom: "Fruits rouges",
    rayon: "Surgelés",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "poivron",
    nom: "Poivron",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "poivre",
    nom: "Poivre",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 2.5,
  },
  {
    id: "cafe",
    nom: "Café",
    rayon: "Boissons",
    unite: "dose",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "citron-vert",
    nom: "Citron vert",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "concombre",
    nom: "Concombre",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "oignon-rouge",
    nom: "Oignon rouge",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "poulet-hache",
    nom: "Poulet haché",
    rayon: "Boucherie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "cumin",
    nom: "Cumin",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 2.5,
  },
  {
    id: "raisin",
    nom: "Raisin",
    rayon: "Fruits et légumes",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "lentilles",
    nom: "Lentilles",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pave-de-saumon",
    nom: "Pavé de saumon",
    rayon: "Poissonnerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "concentre-de-tomate",
    nom: "Concentré de tomate",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5.3,
  },
  {
    id: "sel",
    nom: "Sel",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 6,
  },
  {
    id: "tomates-concassees",
    nom: "Tomates concassées",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "poulet-morceaux-filet-cuisse-pilon",
    nom: "Poulet (morceaux : filet/cuisse/pilon)",
    rayon: "Boucherie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pain-complet-au-levain",
    nom: "Pain complet au levain",
    rayon: "Boulangerie",
    unite: "tranche",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "oignon",
    nom: "Oignon",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "yaourt-grec-nature",
    nom: "Yaourt grec nature",
    rayon: "Crèmerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "salade",
    nom: "Salade",
    rayon: "Fruits et légumes",
    unite: "poignée",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "miel",
    nom: "Miel",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 7,
  },
  {
    id: "haricots-rouges-ou-noirs",
    nom: "Haricots rouges (ou noirs)",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "flocons-d-avoine",
    nom: "Flocons d'avoine",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "avocat",
    nom: "Avocat",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "noix-et-amandes",
    nom: "Noix et amandes",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "houmous",
    nom: "Houmous",
    rayon: "Crèmerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "poisson-en-boite-thon-sardines-maquereau",
    nom: "Poisson en boîte (thon/sardines/maquereau)",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "potiron",
    nom: "Potiron",
    rayon: "Fruits et légumes",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "oeufs",
    nom: "Œufs",
    rayon: "Crèmerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "ail-en-poudre",
    nom: "Ail en poudre",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 3,
  },
  // --- Ajoutés depuis la liste de courses Apple Rappels de Qassim ---
  // Aucun n'est utilisé par un plat pour l'instant : ils ne profitent du
  // mécanisme "essentiel + minimum" qu'une fois réglé dans l'écran Stock.
  {
    id: "curcuma",
    nom: "Curcuma",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "gingembre-moulu",
    nom: "Gingembre moulu",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "graines-de-nigelle",
    nom: "Graines de nigelle (Black seed)",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "fromage-rape",
    nom: "Fromage râpé",
    rayon: "Crèmerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  // --- Compléments alimentaires (nouveau rayon) ---
  {
    id: "zinc-bisglycinate",
    nom: "Zinc bisglycinate",
    rayon: "Compléments alimentaires",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "omega-3",
    nom: "Oméga 3",
    rayon: "Compléments alimentaires",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "vitamine-d-vitamine-k2",
    nom: "Vitamine D + vitamine K2",
    rayon: "Compléments alimentaires",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "magnesium-bisglycinate",
    nom: "Magnésium bisglycinate",
    rayon: "Compléments alimentaires",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "persil",
    nom: "Persil",
    rayon: "Fruits et légumes",
    unite: "bouquet",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "coriandre",
    nom: "Coriandre",
    rayon: "Fruits et légumes",
    unite: "bouquet",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "fromage-de-chevre",
    nom: "Fromage de chèvre",
    rayon: "Crèmerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "fromage-de-brebis",
    nom: "Fromage de brebis",
    rayon: "Crèmerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "boeuf-hache",
    nom: "Bœuf haché",
    rayon: "Boucherie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "agneau-hache",
    nom: "Agneau haché",
    rayon: "Boucherie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "parmesan-rape",
    nom: "Parmesan râpé",
    rayon: "Crèmerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pecorino-rape",
    nom: "Pecorino râpé",
    rayon: "Crèmerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "bacon-de-boeuf",
    nom: "Bacon de bœuf",
    rayon: "Boucherie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "bacon-de-dinde",
    nom: "Bacon de dinde",
    rayon: "Boucherie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "wraps-complets",
    nom: "Wraps complets",
    rayon: "Épicerie salée",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pain-pita",
    nom: "Pain pita",
    rayon: "Boulangerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "boeuf-faux-filet",
    nom: "Bœuf faux-filet",
    rayon: "Boucherie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "boeuf-en-cubes",
    nom: "Bœuf en cubes",
    rayon: "Boucherie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "chili-en-poudre",
    nom: "Chili en poudre",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 2.5,
  },
  {
    id: "piment-doux",
    nom: "Piment doux",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 2.5,
  },
  {
    id: "lait",
    nom: "Lait",
    rayon: "Crèmerie",
    unite: "ml",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "kefir",
    nom: "Kéfir",
    rayon: "Crèmerie",
    unite: "ml",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "carotte",
    nom: "Carotte",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "courgette",
    nom: "Courgette",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "poireau",
    nom: "Poireau",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "champignons-de-paris",
    nom: "Champignons de Paris",
    rayon: "Fruits et légumes",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pomme-de-terre",
    nom: "Pomme de terre",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pomme",
    nom: "Pomme",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "orange",
    nom: "Orange",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "brocoli",
    nom: "Brocoli",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "merguez-halal",
    nom: "Merguez (halal)",
    rayon: "Boucherie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "escalope-de-dinde",
    nom: "Escalope de dinde",
    rayon: "Boucherie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "saucisses-de-volaille-halal",
    nom: "Saucisses de volaille (halal)",
    rayon: "Boucherie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "cabillaud",
    nom: "Cabillaud",
    rayon: "Poissonnerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "crevettes",
    nom: "Crevettes",
    rayon: "Poissonnerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "thon-frais",
    nom: "Thon frais",
    rayon: "Poissonnerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "sole",
    nom: "Sole",
    rayon: "Poissonnerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "dorade",
    nom: "Dorade",
    rayon: "Poissonnerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "moules",
    nom: "Moules",
    rayon: "Poissonnerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "calamars",
    nom: "Calamars",
    rayon: "Poissonnerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "saumon-fume",
    nom: "Saumon fumé",
    rayon: "Poissonnerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "merlan",
    nom: "Merlan",
    rayon: "Poissonnerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "beurre",
    nom: "Beurre",
    rayon: "Crèmerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "creme-fraiche",
    nom: "Crème fraîche",
    rayon: "Crèmerie",
    unite: "ml",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "mozzarella",
    nom: "Mozzarella",
    rayon: "Crèmerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "baguette",
    nom: "Baguette",
    rayon: "Boulangerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pain-de-mie",
    nom: "Pain de mie",
    rayon: "Boulangerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "croissant",
    nom: "Croissant",
    rayon: "Boulangerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "brioche",
    nom: "Brioche",
    rayon: "Boulangerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "naan",
    nom: "Naan",
    rayon: "Boulangerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "petits-pains",
    nom: "Petits pains",
    rayon: "Boulangerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pain-aux-cereales",
    nom: "Pain aux céréales",
    rayon: "Boulangerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "biscottes",
    nom: "Biscottes",
    rayon: "Boulangerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "farine",
    nom: "Farine",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "sauce-soja",
    nom: "Sauce soja",
    rayon: "Épicerie salée",
    unite: "ml",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "moutarde",
    nom: "Moutarde",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "mayonnaise",
    nom: "Mayonnaise",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "vinaigre",
    nom: "Vinaigre",
    rayon: "Épicerie salée",
    unite: "ml",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "semoule",
    nom: "Semoule",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "quinoa",
    nom: "Quinoa",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "sauce-tomate",
    nom: "Sauce tomate",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "sucre",
    nom: "Sucre",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 4,
  },
  {
    id: "confiture",
    nom: "Confiture",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "pate-a-tartiner",
    nom: "Pâte à tartiner",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "chocolat-en-poudre",
    nom: "Chocolat en poudre",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 3,
  },
  {
    id: "cereales",
    nom: "Céréales",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "biscuits",
    nom: "Biscuits",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "levure-chimique",
    nom: "Levure chimique",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 3,
  },
  {
    id: "sirop-d-erable",
    nom: "Sirop d'érable",
    rayon: "Épicerie sucrée",
    unite: "ml",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "cannelle",
    nom: "Cannelle",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 2.5,
  },
  {
    id: "muscade",
    nom: "Muscade",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 2,
  },
  {
    id: "herbes-de-provence",
    nom: "Herbes de Provence",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 1.5,
  },
  {
    id: "origan",
    nom: "Origan",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 1.5,
  },
  {
    id: "thym",
    nom: "Thym",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 1.5,
  },
  {
    id: "laurier",
    nom: "Laurier",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 1,
  },
  {
    id: "legumes-surgeles-melanges",
    nom: "Légumes surgelés mélangés",
    rayon: "Surgelés",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "frites-surgelees",
    nom: "Frites surgelées",
    rayon: "Surgelés",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "petits-pois-surgeles",
    nom: "Petits pois surgelés",
    rayon: "Surgelés",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "poisson-pane",
    nom: "Poisson pané",
    rayon: "Surgelés",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "glace",
    nom: "Glace",
    rayon: "Surgelés",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pizza-surgelee",
    nom: "Pizza surgelée",
    rayon: "Surgelés",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "eau-minerale",
    nom: "Eau minérale",
    rayon: "Boissons",
    unite: "ml",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "jus-d-orange",
    nom: "Jus d'orange",
    rayon: "Boissons",
    unite: "ml",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "the",
    nom: "Thé",
    rayon: "Boissons",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "soda",
    nom: "Soda",
    rayon: "Boissons",
    unite: "ml",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "sirop",
    nom: "Sirop",
    rayon: "Boissons",
    unite: "ml",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "whey-proteine",
    nom: "Whey protéine",
    rayon: "Compléments alimentaires",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "multivitamines",
    nom: "Multivitamines",
    rayon: "Compléments alimentaires",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "dentifrice",
    nom: "Dentifrice",
    rayon: "Hygiène",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "brosse-a-dents",
    nom: "Brosse à dents",
    rayon: "Hygiène",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "deodorant",
    nom: "Déodorant",
    rayon: "Hygiène",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "gel-douche",
    nom: "Gel douche",
    rayon: "Hygiène",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "shampoing",
    nom: "Shampoing",
    rayon: "Hygiène",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "savon",
    nom: "Savon",
    rayon: "Hygiène",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "papier-toilette",
    nom: "Papier toilette",
    rayon: "Hygiène",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "rasoir",
    nom: "Rasoir",
    rayon: "Hygiène",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "coton-tiges",
    nom: "Coton-tiges",
    rayon: "Hygiène",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "protections-hygieniques",
    nom: "Protections hygiéniques",
    rayon: "Hygiène",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "liquide-vaisselle",
    nom: "Liquide vaisselle",
    rayon: "Entretien maison",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "lessive",
    nom: "Lessive",
    rayon: "Entretien maison",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "adoucissant",
    nom: "Adoucissant",
    rayon: "Entretien maison",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "eau-de-javel",
    nom: "Eau de Javel",
    rayon: "Entretien maison",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "nettoyant-multi-usage",
    nom: "Nettoyant multi-usage",
    rayon: "Entretien maison",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "sacs-poubelle",
    nom: "Sacs poubelle",
    rayon: "Entretien maison",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "essuie-tout",
    nom: "Essuie-tout",
    rayon: "Entretien maison",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "anti-calcaire",
    nom: "Anti-calcaire",
    rayon: "Entretien maison",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "eponges",
    nom: "Éponges",
    rayon: "Entretien maison",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "gants-menagers",
    nom: "Gants ménagers",
    rayon: "Entretien maison",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "film-alimentaire",
    nom: "Film alimentaire",
    rayon: "Emballage",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "papier-aluminium",
    nom: "Papier aluminium",
    rayon: "Emballage",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "sacs-congelation",
    nom: "Sacs congélation",
    rayon: "Emballage",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "papier-cuisson",
    nom: "Papier cuisson",
    rayon: "Emballage",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "boites-de-conservation",
    nom: "Boîtes de conservation",
    rayon: "Emballage",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  // --- Ajoutés pour le catalogue de plats "grand public" (30 plats parmi les
  // plus courants en France et dans le monde, voir CLAUDE.md § Catalogue de
  // plats de départ) ---
  {
    id: "aubergine",
    nom: "Aubergine",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "basilic",
    nom: "Basilic",
    rayon: "Fruits et légumes",
    unite: "bouquet",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "menthe-fraiche",
    nom: "Menthe fraîche",
    rayon: "Fruits et légumes",
    unite: "bouquet",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pruneaux",
    nom: "Pruneaux",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "chocolat-noir",
    nom: "Chocolat noir",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "lait-de-coco",
    nom: "Lait de coco",
    rayon: "Épicerie salée",
    unite: "ml",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "bouillon-de-legumes",
    nom: "Bouillon de légumes",
    rayon: "Épicerie salée",
    unite: "cube",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pate-brisee",
    nom: "Pâte brisée",
    rayon: "Crèmerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
];

// --- Catalogue des plats ---
// repas : nom du repas éditable (voir CLAUDE.md § Repas éditables) — "Petit-déjeuner",
//   "Snack/Goûter", "Déjeuner/Dîner", "Dessert", "Entrée", "Accompagnement",
//   "Recette de base" ou "Boisson", résolu en id au chargement (storage.js).
//   Distinct des 5 créneaux fixes de l'écran Semaine.
// materiel : noms (résolus en ids au chargement, voir storage.js) du matériel
//   requis ; tempsPreparation/tempsCuisson : en minutes (0 = pas de cuisson).
// portionsReference : nombre de portions de la recette d'origine (indicatif).
// ingredients[].quantitePortion : quantité nécessaire pour UNE portion, dans
//   l'unité "unite" de la ligne (peut différer de l'unité de stock : conversion
//   cuillère → unite de stock faite par calculs.js via parCuillereACafe).
// etiquettes : ids dérivés des noms par défaut (voir storage.js → genererSlug) —
//   Sucré → "sucre", Salé → "sale", Sain → "sain", Sans porc → "sans-porc",
//   Végétarien → "vegetarien", Végétalien → "vegetalien", Sans gluten →
//   "sans-gluten", Sans lactose → "sans-lactose", Gâteau → "gateau", Rapide à
//   préparer → "rapide-a-preparer", Économique → "economique".
//
// 30 plats parmi les plus courants en France et dans le monde (décision
// Qassim : rendre l'app "grand public" — voir CLAUDE.md § Catalogue de plats
// de départ), au moins un par repas éditable et par étiquette de départ.
export const plats = [
  {
    id: "tartines-beurre-confiture",
    nom: "Tartines beurre & confiture",
    repas: "Petit-déjeuner",
    materiel: ["Grille-pain"],
    tempsPreparation: 3,
    tempsCuisson: 2,
    portionsReference: 1,
    etapes: "1. Fais griller 2 tranches de pain de mie au grille-pain.\n2. Beurre encore chaud, puis étale la confiture.",
    etiquettes: ["sucre", "rapide-a-preparer", "economique"],
    ingredients: [
      { ingredientId: "pain-de-mie", quantitePortion: 2, unite: "pièce" },
      { ingredientId: "beurre", quantitePortion: 1, unite: "c. à soupe" },
      { ingredientId: "confiture", quantitePortion: 2, unite: "c. à soupe" },
    ],
  },
  {
    id: "porridge-avoine",
    nom: "Porridge à l'avoine",
    repas: "Petit-déjeuner",
    materiel: ["Casserole"],
    tempsPreparation: 2,
    tempsCuisson: 5,
    portionsReference: 1,
    etapes: "1. Fais chauffer le lait et les flocons d'avoine à feu doux 5 min, en remuant.\n2. Verse dans un bol, ajoute le miel et la banane coupée en rondelles.",
    etiquettes: ["sain", "vegetarien", "economique", "rapide-a-preparer"],
    ingredients: [
      { ingredientId: "flocons-d-avoine", quantitePortion: 50, unite: "g" },
      { ingredientId: "lait", quantitePortion: 200, unite: "ml" },
      { ingredientId: "miel", quantitePortion: 1, unite: "c. à café" },
      { ingredientId: "banane", quantitePortion: 0.5, unite: "pièce" },
    ],
  },
  {
    id: "pain-perdu",
    nom: "Pain perdu",
    repas: "Petit-déjeuner",
    materiel: ["Poêle"],
    tempsPreparation: 5,
    tempsCuisson: 6,
    portionsReference: 2,
    etapes: "1. Bats les œufs avec le lait, le sucre et la cannelle dans une assiette creuse.\n2. Trempe chaque tranche de pain des deux côtés.\n3. Fais dorer 2–3 min par face dans le beurre chaud.",
    etiquettes: ["sucre", "economique"],
    ingredients: [
      { ingredientId: "pain-de-mie", quantitePortion: 2, unite: "pièce" },
      { ingredientId: "oeufs", quantitePortion: 1, unite: "pièce" },
      { ingredientId: "lait", quantitePortion: 50, unite: "ml" },
      { ingredientId: "sucre", quantitePortion: 10, unite: "g" },
      { ingredientId: "cannelle", quantitePortion: 0.5, unite: "g" },
      { ingredientId: "beurre", quantitePortion: 1, unite: "c. à café" },
    ],
  },
  {
    id: "tartine-banane-beurre-de-cacahuete",
    nom: "Tartine banane & beurre de cacahuète",
    repas: "Snack/Goûter",
    materiel: [],
    tempsPreparation: 5,
    tempsCuisson: 0,
    portionsReference: 1,
    etapes: "1. Étale le beurre de cacahuète sur le pain.\n2. Ajoute la banane coupée en rondelles, un filet de miel par-dessus.",
    etiquettes: ["sucre", "vegetarien", "rapide-a-preparer"],
    ingredients: [
      { ingredientId: "pain-complet-au-levain", quantitePortion: 2, unite: "tranche" },
      { ingredientId: "beurre-de-cacahuete-100-arachide", quantitePortion: 30, unite: "g" },
      { ingredientId: "banane", quantitePortion: 1, unite: "pièce" },
      { ingredientId: "miel", quantitePortion: 1, unite: "c. à café" },
    ],
  },
  {
    id: "compote-de-pomme-maison",
    nom: "Compote de pomme maison",
    repas: "Snack/Goûter",
    materiel: ["Casserole"],
    tempsPreparation: 10,
    tempsCuisson: 20,
    portionsReference: 4,
    etapes: "1. Épluche et coupe les pommes en morceaux.\n2. Casserole avec un fond d'eau, le sucre et la cannelle, feu doux 20 min à couvert en remuant de temps en temps.\n3. Écrase à la fourchette selon la texture voulue.",
    etiquettes: ["sain", "vegetalien", "sans-gluten", "sans-lactose", "economique"],
    ingredients: [
      { ingredientId: "pomme", quantitePortion: 1.5, unite: "pièce" },
      { ingredientId: "sucre", quantitePortion: 10, unite: "g" },
      { ingredientId: "cannelle", quantitePortion: 0.5, unite: "g" },
    ],
  },
  {
    id: "smoothie-banane-fruits-rouges",
    nom: "Smoothie banane-fruits rouges",
    repas: "Boisson",
    materiel: ["Mixeur"],
    tempsPreparation: 5,
    tempsCuisson: 0,
    portionsReference: 2,
    etapes: "1. Mixe la banane, les fruits rouges, le lait et le miel jusqu'à texture lisse.\n2. Sers immédiatement, bien frais.",
    etiquettes: ["sain", "rapide-a-preparer"],
    ingredients: [
      { ingredientId: "banane", quantitePortion: 1, unite: "pièce" },
      { ingredientId: "fruits-rouges", quantitePortion: 80, unite: "g" },
      { ingredientId: "lait", quantitePortion: 150, unite: "ml" },
      { ingredientId: "miel", quantitePortion: 1, unite: "c. à café" },
    ],
  },
  {
    id: "the-a-la-menthe",
    nom: "Thé à la menthe",
    repas: "Boisson",
    materiel: ["Casserole"],
    tempsPreparation: 2,
    tempsCuisson: 5,
    portionsReference: 2,
    etapes: "1. Porte l'eau à ébullition dans la casserole.\n2. Verse sur le thé et la menthe fraîche dans la théière, laisse infuser 4–5 min.\n3. Sucre selon le goût, sers chaud.",
    etiquettes: ["vegetalien", "sans-gluten", "sans-lactose", "economique", "rapide-a-preparer"],
    ingredients: [
      { ingredientId: "the", quantitePortion: 2, unite: "g" },
      { ingredientId: "menthe-fraiche", quantitePortion: 0.5, unite: "bouquet" },
      { ingredientId: "sucre", quantitePortion: 10, unite: "g" },
    ],
  },
  {
    id: "salade-caprese",
    nom: "Salade caprese (tomate, mozzarella, basilic)",
    repas: "Entrée",
    materiel: [],
    tempsPreparation: 10,
    tempsCuisson: 0,
    portionsReference: 2,
    etapes: "1. Coupe les tomates et la mozzarella en tranches, alterne-les dans l'assiette.\n2. Parsème de feuilles de basilic.\n3. Arrose d'huile d'olive, sel et poivre.",
    etiquettes: ["vegetarien", "sain", "sans-gluten", "rapide-a-preparer"],
    ingredients: [
      { ingredientId: "tomates", quantitePortion: 2, unite: "pièce" },
      { ingredientId: "mozzarella", quantitePortion: 125, unite: "g" },
      { ingredientId: "basilic", quantitePortion: 0.5, unite: "bouquet" },
      { ingredientId: "huile-d-olive", quantitePortion: 1, unite: "c. à soupe" },
      { ingredientId: "sel", quantitePortion: 0.5, unite: "c. à café" },
      { ingredientId: "poivre", quantitePortion: 0.25, unite: "c. à café" },
    ],
  },
  {
    id: "veloute-de-potiron",
    nom: "Velouté de potiron",
    repas: "Entrée",
    materiel: ["Casserole", "Mixeur"],
    tempsPreparation: 15,
    tempsCuisson: 25,
    portionsReference: 4,
    etapes: "1. Fais revenir l'oignon émincé dans l'huile d'olive 3 min.\n2. Ajoute le potiron en dés et le bouillon de légumes (dilué dans l'eau selon le paquet), 20 min à feu doux.\n3. Mixe, assaisonne avec la muscade, le sel et le poivre.",
    etiquettes: ["vegetalien", "sain", "sans-gluten", "sans-lactose", "economique"],
    ingredients: [
      { ingredientId: "potiron", quantitePortion: 200, unite: "g" },
      { ingredientId: "oignon", quantitePortion: 0.25, unite: "pièce" },
      { ingredientId: "bouillon-de-legumes", quantitePortion: 0.5, unite: "cube" },
      { ingredientId: "huile-d-olive", quantitePortion: 0.25, unite: "c. à soupe" },
      { ingredientId: "muscade", quantitePortion: 0.25, unite: "g" },
      { ingredientId: "sel", quantitePortion: 0.25, unite: "c. à café" },
      { ingredientId: "poivre", quantitePortion: 0.125, unite: "c. à café" },
    ],
  },
  {
    id: "puree-de-pommes-de-terre",
    nom: "Purée de pommes de terre",
    repas: "Accompagnement",
    materiel: ["Casserole"],
    tempsPreparation: 15,
    tempsCuisson: 20,
    portionsReference: 4,
    etapes: "1. Épluche et coupe les pommes de terre, cuis 20 min à l'eau bouillante salée.\n2. Égoutte, écrase, ajoute le beurre et le lait chaud petit à petit.\n3. Assaisonne avec le sel, le poivre et la muscade.",
    etiquettes: ["vegetarien", "sans-gluten", "economique"],
    ingredients: [
      { ingredientId: "pomme-de-terre", quantitePortion: 1.5, unite: "pièce" },
      { ingredientId: "lait", quantitePortion: 37.5, unite: "ml" },
      { ingredientId: "beurre", quantitePortion: 10, unite: "g" },
      { ingredientId: "sel", quantitePortion: 0.25, unite: "c. à café" },
      { ingredientId: "poivre", quantitePortion: 0.125, unite: "c. à café" },
      { ingredientId: "muscade", quantitePortion: 0.125, unite: "g" },
    ],
  },
  {
    id: "riz-pilaf",
    nom: "Riz pilaf",
    repas: "Accompagnement",
    materiel: ["Cuiseur à riz"],
    tempsPreparation: 5,
    tempsCuisson: 18,
    portionsReference: 4,
    etapes: "1. Fais revenir l'oignon émincé dans l'huile d'olive 2 min.\n2. Ajoute le riz, remue 1 min, puis le bouillon de légumes dilué.\n3. Cuis selon le programme du cuiseur à riz (ou 18 min à couvert à la casserole).",
    etiquettes: ["vegetalien", "sans-gluten", "sans-lactose", "economique", "rapide-a-preparer"],
    ingredients: [
      { ingredientId: "riz", quantitePortion: 75, unite: "g" },
      { ingredientId: "oignon", quantitePortion: 0.125, unite: "pièce" },
      { ingredientId: "bouillon-de-legumes", quantitePortion: 0.25, unite: "cube" },
      { ingredientId: "huile-d-olive", quantitePortion: 0.25, unite: "c. à soupe" },
      { ingredientId: "sel", quantitePortion: 0.125, unite: "c. à café" },
    ],
  },
  {
    id: "gratin-dauphinois",
    nom: "Gratin dauphinois",
    repas: "Accompagnement",
    materiel: ["Four"],
    tempsPreparation: 20,
    tempsCuisson: 45,
    portionsReference: 6,
    etapes: "1. Épluche et coupe les pommes de terre en fines rondelles.\n2. Frotte un plat à gratin avec l'ail, beurre-le.\n3. Range les pommes de terre, verse le lait et la crème mélangés, sel, poivre, muscade.\n4. Parsème de fromage râpé, four 180°C, 45 min.",
    etiquettes: ["vegetarien", "sans-gluten", "economique"],
    ingredients: [
      { ingredientId: "pomme-de-terre", quantitePortion: 1.33, unite: "pièce" },
      { ingredientId: "creme-fraiche", quantitePortion: 50, unite: "ml" },
      { ingredientId: "lait", quantitePortion: 33.3, unite: "ml" },
      { ingredientId: "ail", quantitePortion: 0.33, unite: "gousse" },
      { ingredientId: "fromage-rape", quantitePortion: 25, unite: "g" },
      { ingredientId: "beurre", quantitePortion: 3.33, unite: "g" },
      { ingredientId: "sel", quantitePortion: 0.17, unite: "c. à café" },
      { ingredientId: "poivre", quantitePortion: 0.08, unite: "c. à café" },
      { ingredientId: "muscade", quantitePortion: 0.17, unite: "g" },
    ],
  },
  {
    id: "boeuf-bourguignon",
    nom: "Bœuf bourguignon",
    repas: "Déjeuner/Dîner",
    materiel: ["Casserole"],
    tempsPreparation: 25,
    tempsCuisson: 150,
    portionsReference: 4,
    etapes: "1. Fais dorer le bœuf en cubes dans l'huile d'olive, réserve.\n2. Fais revenir l'oignon, l'ail et les champignons émincés.\n3. Remets la viande, saupoudre de farine, remue 1 min.\n4. Ajoute le concentré de tomate, la carotte en rondelles, le laurier, le thym, couvre d'eau. Mijote 2h30 à couvert.\n5. Sel, poivre en fin de cuisson.",
    etiquettes: ["sale"],
    ingredients: [
      { ingredientId: "boeuf-en-cubes", quantitePortion: 200, unite: "g" },
      { ingredientId: "oignon", quantitePortion: 0.5, unite: "pièce" },
      { ingredientId: "carotte", quantitePortion: 0.75, unite: "pièce" },
      { ingredientId: "ail", quantitePortion: 0.5, unite: "gousse" },
      { ingredientId: "champignons-de-paris", quantitePortion: 62.5, unite: "g" },
      { ingredientId: "farine", quantitePortion: 5, unite: "g" },
      { ingredientId: "concentre-de-tomate", quantitePortion: 7.5, unite: "g" },
      { ingredientId: "laurier", quantitePortion: 0.25, unite: "g" },
      { ingredientId: "thym", quantitePortion: 0.25, unite: "g" },
      { ingredientId: "sel", quantitePortion: 0.25, unite: "c. à café" },
      { ingredientId: "poivre", quantitePortion: 0.125, unite: "c. à café" },
      { ingredientId: "huile-d-olive", quantitePortion: 0.25, unite: "c. à soupe" },
    ],
  },
  {
    id: "ratatouille",
    nom: "Ratatouille",
    repas: "Déjeuner/Dîner",
    materiel: ["Casserole"],
    tempsPreparation: 20,
    tempsCuisson: 40,
    portionsReference: 4,
    etapes: "1. Coupe l'aubergine, la courgette, le poivron et les tomates en dés.\n2. Fais revenir l'oignon et l'ail dans l'huile d'olive 3 min.\n3. Ajoute les légumes un par un (les plus fermes d'abord), herbes de Provence, sel, poivre.\n4. Mijote 40 min à couvert en remuant de temps en temps.",
    etiquettes: ["vegetarien", "vegetalien", "sain", "sans-gluten", "sans-porc", "sans-lactose", "economique"],
    ingredients: [
      { ingredientId: "aubergine", quantitePortion: 0.5, unite: "pièce" },
      { ingredientId: "courgette", quantitePortion: 0.5, unite: "pièce" },
      { ingredientId: "poivron", quantitePortion: 0.5, unite: "pièce" },
      { ingredientId: "tomates", quantitePortion: 1, unite: "pièce" },
      { ingredientId: "oignon", quantitePortion: 0.25, unite: "pièce" },
      { ingredientId: "ail", quantitePortion: 0.5, unite: "gousse" },
      { ingredientId: "huile-d-olive", quantitePortion: 0.5, unite: "c. à soupe" },
      { ingredientId: "herbes-de-provence", quantitePortion: 0.5, unite: "g" },
      { ingredientId: "sel", quantitePortion: 0.25, unite: "c. à café" },
      { ingredientId: "poivre", quantitePortion: 0.125, unite: "c. à café" },
    ],
  },
  {
    id: "couscous-poulet-merguez",
    nom: "Couscous poulet & merguez",
    repas: "Déjeuner/Dîner",
    materiel: ["Casserole", "Cuiseur vapeur"],
    tempsPreparation: 25,
    tempsCuisson: 45,
    portionsReference: 4,
    etapes: "1. Fais dorer le poulet, réserve. Fais revenir l'oignon, ajoute carotte, courgette, pois chiches, tomates concassées, cumin, curcuma, couvre d'eau, mijote 30 min.\n2. Remets le poulet 10 min avant la fin. Fais cuire les merguez à part à la poêle ou au four.\n3. Prépare la semoule à la vapeur (ou selon le paquet), arrose d'huile d'olive.\n4. Sers la semoule avec le bouillon, les légumes, le poulet et les merguez.",
    etiquettes: ["sale", "sans-porc"],
    ingredients: [
      { ingredientId: "semoule", quantitePortion: 100, unite: "g" },
      { ingredientId: "poulet-morceaux-filet-cuisse-pilon", quantitePortion: 150, unite: "g" },
      { ingredientId: "merguez-halal", quantitePortion: 100, unite: "g" },
      { ingredientId: "carotte", quantitePortion: 1, unite: "pièce" },
      { ingredientId: "courgette", quantitePortion: 0.5, unite: "pièce" },
      { ingredientId: "pois-chiches", quantitePortion: 50, unite: "g" },
      { ingredientId: "oignon", quantitePortion: 0.25, unite: "pièce" },
      { ingredientId: "tomates-concassees", quantitePortion: 50, unite: "g" },
      { ingredientId: "cumin", quantitePortion: 0.5, unite: "g" },
      { ingredientId: "curcuma", quantitePortion: 0.5, unite: "g" },
      { ingredientId: "huile-d-olive", quantitePortion: 0.25, unite: "c. à soupe" },
      { ingredientId: "sel", quantitePortion: 0.25, unite: "c. à café" },
    ],
  },
  {
    id: "blanquette-de-poulet",
    nom: "Blanquette de poulet",
    repas: "Déjeuner/Dîner",
    materiel: ["Casserole"],
    tempsPreparation: 20,
    tempsCuisson: 45,
    portionsReference: 4,
    etapes: "1. Pochee le poulet avec la carotte, le poireau et le bouillon 30 min à petits frémissements.\n2. Retire le poulet et les légumes, garde le bouillon.\n3. Fais un roux (beurre + farine), délaye avec le bouillon, ajoute les champignons émincés 10 min.\n4. Hors du feu, ajoute la crème fraîche, remets poulet et légumes, sel, poivre.",
    etiquettes: ["sale"],
    ingredients: [
      { ingredientId: "poulet-morceaux-filet-cuisse-pilon", quantitePortion: 200, unite: "g" },
      { ingredientId: "carotte", quantitePortion: 0.75, unite: "pièce" },
      { ingredientId: "poireau", quantitePortion: 0.5, unite: "pièce" },
      { ingredientId: "champignons-de-paris", quantitePortion: 50, unite: "g" },
      { ingredientId: "creme-fraiche", quantitePortion: 50, unite: "ml" },
      { ingredientId: "beurre", quantitePortion: 7.5, unite: "g" },
      { ingredientId: "farine", quantitePortion: 7.5, unite: "g" },
      { ingredientId: "bouillon-de-volaille-halal", quantitePortion: 0.25, unite: "cube" },
      { ingredientId: "sel", quantitePortion: 0.25, unite: "c. à café" },
      { ingredientId: "poivre", quantitePortion: 0.125, unite: "c. à café" },
    ],
  },
  {
    id: "steak-frites",
    nom: "Steak-frites",
    repas: "Déjeuner/Dîner",
    materiel: ["Poêle", "Air fryer"],
    tempsPreparation: 5,
    tempsCuisson: 15,
    portionsReference: 1,
    etapes: "1. Frites. Air fryer 200°C, 12–15 min, secoue à mi-cuisson.\n2. Steak. Poêle très chaude avec un peu de beurre, 2–3 min par face selon la cuisson voulue.\n3. Sel, poivre, sers immédiatement.",
    etiquettes: ["sale"],
    ingredients: [
      { ingredientId: "boeuf-faux-filet", quantitePortion: 200, unite: "g" },
      { ingredientId: "frites-surgelees", quantitePortion: 200, unite: "g" },
      { ingredientId: "beurre", quantitePortion: 10, unite: "g" },
      { ingredientId: "sel", quantitePortion: 1, unite: "c. à café" },
      { ingredientId: "poivre", quantitePortion: 0.5, unite: "c. à café" },
    ],
  },
  {
    id: "poulet-roti-pommes-de-terre",
    nom: "Poulet rôti & pommes de terre",
    repas: "Déjeuner/Dîner",
    materiel: ["Four"],
    tempsPreparation: 15,
    tempsCuisson: 60,
    portionsReference: 4,
    etapes: "1. Frotte le poulet avec l'huile d'olive, l'ail écrasé, le thym, le laurier, sel et poivre.\n2. Dispose les pommes de terre coupées en quartiers autour dans le plat.\n3. Four 200°C, 1h, arrose de temps en temps avec le jus.",
    etiquettes: ["sale", "sans-gluten", "sans-porc"],
    ingredients: [
      { ingredientId: "poulet-morceaux-filet-cuisse-pilon", quantitePortion: 250, unite: "g" },
      { ingredientId: "pomme-de-terre", quantitePortion: 1.5, unite: "pièce" },
      { ingredientId: "ail", quantitePortion: 1, unite: "gousse" },
      { ingredientId: "thym", quantitePortion: 0.5, unite: "g" },
      { ingredientId: "laurier", quantitePortion: 0.25, unite: "g" },
      { ingredientId: "huile-d-olive", quantitePortion: 0.5, unite: "c. à soupe" },
      { ingredientId: "sel", quantitePortion: 0.25, unite: "c. à café" },
      { ingredientId: "poivre", quantitePortion: 0.125, unite: "c. à café" },
    ],
  },
  {
    id: "chili-con-carne",
    nom: "Chili con carne",
    repas: "Déjeuner/Dîner",
    materiel: ["Casserole"],
    tempsPreparation: 15,
    tempsCuisson: 35,
    portionsReference: 4,
    etapes: "1. Fais revenir le bœuf haché avec l'oignon, le poivron et l'ail.\n2. Ajoute les tomates concassées, le concentré de tomate, les haricots, le chili en poudre et le cumin.\n3. Mijote 30 min à couvert, sel selon le goût.",
    etiquettes: ["sale", "sans-gluten", "sans-lactose"],
    ingredients: [
      { ingredientId: "boeuf-hache", quantitePortion: 150, unite: "g" },
      { ingredientId: "haricots-rouges-ou-noirs", quantitePortion: 100, unite: "g" },
      { ingredientId: "tomates-concassees", quantitePortion: 100, unite: "g" },
      { ingredientId: "oignon", quantitePortion: 0.25, unite: "pièce" },
      { ingredientId: "poivron", quantitePortion: 0.25, unite: "pièce" },
      { ingredientId: "ail", quantitePortion: 0.5, unite: "gousse" },
      { ingredientId: "chili-en-poudre", quantitePortion: 1, unite: "g" },
      { ingredientId: "cumin", quantitePortion: 0.5, unite: "g" },
      { ingredientId: "concentre-de-tomate", quantitePortion: 7.5, unite: "g" },
      { ingredientId: "sel", quantitePortion: 0.25, unite: "c. à café" },
    ],
  },
  {
    id: "pates-carbonara",
    nom: "Pâtes à la carbonara",
    repas: "Déjeuner/Dîner",
    materiel: ["Casserole", "Poêle"],
    tempsPreparation: 10,
    tempsCuisson: 15,
    portionsReference: 2,
    etapes: "1. Cuis les pâtes al dente dans l'eau bouillante salée.\n2. Fais dorer le bacon de bœuf à la poêle.\n3. Bats les œufs avec le parmesan et le poivre hors du feu.\n4. Égoutte les pâtes, mélange avec le bacon puis avec les œufs battus hors du feu (la chaleur des pâtes suffit à cuire l'œuf).",
    etiquettes: ["sale", "rapide-a-preparer", "sans-porc"],
    ingredients: [
      { ingredientId: "pates-spaghetti", quantitePortion: 100, unite: "g" },
      { ingredientId: "bacon-de-boeuf", quantitePortion: 75, unite: "g" },
      { ingredientId: "oeufs", quantitePortion: 1, unite: "pièce" },
      { ingredientId: "parmesan-rape", quantitePortion: 30, unite: "g" },
      { ingredientId: "poivre", quantitePortion: 0.5, unite: "g" },
    ],
  },
  {
    id: "curry-de-cabillaud-lait-de-coco",
    nom: "Curry de cabillaud au lait de coco",
    repas: "Déjeuner/Dîner",
    materiel: ["Casserole"],
    tempsPreparation: 15,
    tempsCuisson: 20,
    portionsReference: 2,
    etapes: "1. Fais revenir l'oignon et l'ail dans l'huile d'olive.\n2. Ajoute le curcuma, le gingembre, les tomates concassées et le lait de coco, 5 min à frémissement.\n3. Dépose le cabillaud, cuis 10 min à couvert sans remuer fort (le poisson s'effeuille facilement).\n4. Sers avec le riz.",
    etiquettes: ["sain", "sans-gluten", "sans-lactose", "sans-porc"],
    ingredients: [
      { ingredientId: "cabillaud", quantitePortion: 150, unite: "g" },
      { ingredientId: "lait-de-coco", quantitePortion: 200, unite: "ml" },
      { ingredientId: "curcuma", quantitePortion: 1, unite: "g" },
      { ingredientId: "gingembre-moulu", quantitePortion: 1, unite: "g" },
      { ingredientId: "oignon", quantitePortion: 0.5, unite: "pièce" },
      { ingredientId: "ail", quantitePortion: 1, unite: "gousse" },
      { ingredientId: "tomates-concassees", quantitePortion: 50, unite: "g" },
      { ingredientId: "riz", quantitePortion: 75, unite: "g" },
      { ingredientId: "huile-d-olive", quantitePortion: 0.5, unite: "c. à soupe" },
      { ingredientId: "sel", quantitePortion: 0.5, unite: "c. à café" },
    ],
  },
  {
    id: "riz-cantonais",
    nom: "Riz cantonais",
    repas: "Déjeuner/Dîner",
    materiel: ["Poêle"],
    tempsPreparation: 10,
    tempsCuisson: 10,
    portionsReference: 2,
    etapes: "1. Fais revenir le bacon de dinde en dés et les petits pois dans l'huile d'olive.\n2. Pousse sur le côté, casse les œufs dans la poêle, brouille-les rapidement.\n3. Ajoute le riz cuit (froid de préférence), la sauce soja, mélange 3–4 min à feu vif.",
    etiquettes: ["sale", "economique", "rapide-a-preparer"],
    ingredients: [
      { ingredientId: "riz", quantitePortion: 150, unite: "g" },
      { ingredientId: "oeufs", quantitePortion: 1, unite: "pièce" },
      { ingredientId: "petits-pois-surgeles", quantitePortion: 50, unite: "g" },
      { ingredientId: "bacon-de-dinde", quantitePortion: 50, unite: "g" },
      { ingredientId: "sauce-soja", quantitePortion: 1, unite: "c. à soupe" },
      { ingredientId: "huile-d-olive", quantitePortion: 0.5, unite: "c. à soupe" },
    ],
  },
  {
    id: "falafels-houmous",
    nom: "Falafels & houmous",
    repas: "Déjeuner/Dîner",
    materiel: ["Mixeur", "Poêle"],
    tempsPreparation: 20,
    tempsCuisson: 15,
    portionsReference: 4,
    etapes: "1. Mixe les pois chiches (crus, trempés la veille, ou en boîte bien égouttés) avec l'oignon, l'ail, la coriandre, le cumin, la farine et le sel jusqu'à obtenir une pâte grossière.\n2. Forme des petites boulettes aplaties.\n3. Fais-les dorer 3–4 min par face dans l'huile d'olive.\n4. Sers avec le houmous.",
    etiquettes: ["vegetarien", "vegetalien", "sain", "sans-porc", "sans-lactose"],
    ingredients: [
      { ingredientId: "pois-chiches", quantitePortion: 100, unite: "g" },
      { ingredientId: "oignon", quantitePortion: 0.25, unite: "pièce" },
      { ingredientId: "ail", quantitePortion: 0.5, unite: "gousse" },
      { ingredientId: "coriandre", quantitePortion: 0.25, unite: "bouquet" },
      { ingredientId: "cumin", quantitePortion: 1, unite: "g" },
      { ingredientId: "farine", quantitePortion: 5, unite: "g" },
      { ingredientId: "huile-d-olive", quantitePortion: 0.75, unite: "c. à soupe" },
      { ingredientId: "sel", quantitePortion: 0.25, unite: "c. à café" },
      { ingredientId: "houmous", quantitePortion: 50, unite: "g" },
    ],
  },
  {
    id: "tajine-kefta-agneau-pruneaux",
    nom: "Tajine de kefta d'agneau aux pruneaux",
    repas: "Déjeuner/Dîner",
    materiel: ["Casserole"],
    tempsPreparation: 20,
    tempsCuisson: 50,
    portionsReference: 4,
    etapes: "1. Mélange l'agneau haché avec la moitié de l'oignon émincé, la cannelle, le gingembre et le sel. Forme des boulettes.\n2. Fais revenir le reste de l'oignon dans l'huile d'olive, ajoute les boulettes, dore-les.\n3. Ajoute les pruneaux, le miel et un peu d'eau, mijote 40 min à couvert.\n4. Parsème de coriandre fraîche avant de servir.",
    etiquettes: ["sale", "sans-porc"],
    ingredients: [
      { ingredientId: "agneau-hache", quantitePortion: 150, unite: "g" },
      { ingredientId: "oignon", quantitePortion: 0.5, unite: "pièce" },
      { ingredientId: "pruneaux", quantitePortion: 50, unite: "g" },
      { ingredientId: "cannelle", quantitePortion: 0.5, unite: "g" },
      { ingredientId: "gingembre-moulu", quantitePortion: 0.5, unite: "g" },
      { ingredientId: "miel", quantitePortion: 0.5, unite: "c. à soupe" },
      { ingredientId: "coriandre", quantitePortion: 0.25, unite: "bouquet" },
      { ingredientId: "huile-d-olive", quantitePortion: 0.25, unite: "c. à soupe" },
      { ingredientId: "sel", quantitePortion: 0.25, unite: "c. à café" },
    ],
  },
  {
    id: "crepes",
    nom: "Crêpes",
    repas: "Dessert",
    materiel: ["Poêle", "Micro-ondes"],
    tempsPreparation: 10,
    tempsCuisson: 20,
    portionsReference: 8,
    etapes: "1. Mélange la farine, le sucre et le sel, creuse un puits, casse les œufs.\n2. Délaye avec le lait petit à petit pour éviter les grumeaux.\n3. Fais fondre le beurre 20 sec au micro-ondes, ajoute-le à la pâte, laisse reposer 30 min si possible.\n4. Cuis 1–2 min par face dans une poêle chaude légèrement beurrée.",
    etiquettes: ["sucre"],
    ingredients: [
      { ingredientId: "farine", quantitePortion: 31.25, unite: "g" },
      { ingredientId: "oeufs", quantitePortion: 0.375, unite: "pièce" },
      { ingredientId: "lait", quantitePortion: 62.5, unite: "ml" },
      { ingredientId: "sucre", quantitePortion: 2.5, unite: "g" },
      { ingredientId: "sel", quantitePortion: 0.125, unite: "g" },
      { ingredientId: "beurre", quantitePortion: 2.5, unite: "g" },
    ],
  },
  {
    id: "tarte-aux-pommes",
    nom: "Tarte aux pommes",
    repas: "Dessert",
    materiel: ["Four", "Balance de cuisine"],
    tempsPreparation: 20,
    tempsCuisson: 35,
    portionsReference: 6,
    etapes: "1. Étale la pâte brisée dans un moule à tarte, pique le fond à la fourchette.\n2. Épluche et coupe les pommes en fines lamelles, dispose-les en rosace.\n3. Saupoudre de sucre et de cannelle, parsème de noisettes de beurre.\n4. Four 180°C, 35 min, jusqu'à ce que les bords soient dorés.",
    etiquettes: ["sucre", "gateau"],
    ingredients: [
      { ingredientId: "pate-brisee", quantitePortion: 0.17, unite: "pièce" },
      { ingredientId: "pomme", quantitePortion: 0.83, unite: "pièce" },
      { ingredientId: "sucre", quantitePortion: 10, unite: "g" },
      { ingredientId: "cannelle", quantitePortion: 0.33, unite: "g" },
      { ingredientId: "beurre", quantitePortion: 3.33, unite: "g" },
    ],
  },
  {
    id: "mousse-au-chocolat",
    nom: "Mousse au chocolat",
    repas: "Dessert",
    materiel: ["Bol", "Micro-ondes"],
    tempsPreparation: 20,
    tempsCuisson: 0,
    portionsReference: 4,
    etapes: "1. Fais fondre le chocolat en morceaux avec le beurre au micro-ondes (30 sec par 30 sec, en remuant).\n2. Sépare les blancs des jaunes d'œufs. Mélange les jaunes et le sucre au chocolat fondu tiédi.\n3. Monte les blancs en neige ferme, incorpore-les délicatement.\n4. Répartis dans des verrines, frigo au moins 2h avant de servir.",
    etiquettes: ["sucre", "gateau", "sans-gluten"],
    ingredients: [
      { ingredientId: "chocolat-noir", quantitePortion: 50, unite: "g" },
      { ingredientId: "oeufs", quantitePortion: 1, unite: "pièce" },
      { ingredientId: "sucre", quantitePortion: 7.5, unite: "g" },
      { ingredientId: "beurre", quantitePortion: 5, unite: "g" },
    ],
  },
  {
    id: "salade-de-fruits",
    nom: "Salade de fruits",
    repas: "Dessert",
    materiel: ["Bol"],
    tempsPreparation: 15,
    tempsCuisson: 0,
    portionsReference: 4,
    etapes: "1. Coupe la pomme, l'orange et la banane en morceaux.\n2. Ajoute le raisin, arrose de jus de citron pour éviter que les fruits ne noircissent.\n3. Ajoute un filet de miel, mélange, frigo au moins 30 min avant de servir.",
    etiquettes: ["sucre", "sain", "vegetalien", "sans-gluten", "sans-lactose", "economique", "rapide-a-preparer"],
    ingredients: [
      { ingredientId: "pomme", quantitePortion: 0.5, unite: "pièce" },
      { ingredientId: "orange", quantitePortion: 0.5, unite: "pièce" },
      { ingredientId: "banane", quantitePortion: 0.5, unite: "pièce" },
      { ingredientId: "raisin", quantitePortion: 50, unite: "g" },
      { ingredientId: "citron", quantitePortion: 0.25, unite: "pièce" },
      { ingredientId: "miel", quantitePortion: 0.25, unite: "c. à soupe" },
    ],
  },
  {
    id: "vinaigrette-maison",
    nom: "Vinaigrette maison",
    repas: "Recette de base",
    materiel: ["Bol"],
    tempsPreparation: 5,
    tempsCuisson: 0,
    portionsReference: 4,
    etapes: "1. Mélange la moutarde, le vinaigre, le sel et le poivre dans un bol.\n2. Ajoute l'huile d'olive petit à petit en fouettant pour émulsionner.\n3. Se conserve 1 semaine au frigo dans un bocal fermé.",
    etiquettes: ["vegetalien", "sans-gluten", "sans-lactose", "economique", "rapide-a-preparer"],
    ingredients: [
      { ingredientId: "huile-d-olive", quantitePortion: 1, unite: "c. à soupe" },
      { ingredientId: "vinaigre", quantitePortion: 0.5, unite: "c. à soupe" },
      { ingredientId: "moutarde", quantitePortion: 0.25, unite: "c. à café" },
      { ingredientId: "sel", quantitePortion: 0.125, unite: "c. à café" },
      { ingredientId: "poivre", quantitePortion: 0.0625, unite: "c. à café" },
    ],
  },
  {
    id: "bouillon-de-legumes-maison",
    nom: "Bouillon de légumes maison",
    repas: "Recette de base",
    materiel: ["Casserole"],
    tempsPreparation: 10,
    tempsCuisson: 45,
    portionsReference: 6,
    etapes: "1. Épluche et coupe grossièrement la carotte, le poireau et l'oignon.\n2. Mets tout dans une grande casserole avec l'ail, le laurier, le thym et le sel, couvre largement d'eau.\n3. Porte à ébullition puis laisse mijoter 45 min à couvert.\n4. Filtre, se conserve 3 jours au frigo ou se congèle en portions.",
    etiquettes: ["vegetalien", "sain", "sans-gluten", "sans-lactose", "economique"],
    ingredients: [
      { ingredientId: "carotte", quantitePortion: 0.5, unite: "pièce" },
      { ingredientId: "poireau", quantitePortion: 0.33, unite: "pièce" },
      { ingredientId: "oignon", quantitePortion: 0.33, unite: "pièce" },
      { ingredientId: "ail", quantitePortion: 0.33, unite: "gousse" },
      { ingredientId: "laurier", quantitePortion: 0.17, unite: "g" },
      { ingredientId: "thym", quantitePortion: 0.17, unite: "g" },
      { ingredientId: "sel", quantitePortion: 0.17, unite: "c. à café" },
    ],
  },
  // --- Recettes personnelles de Qassim, alignées sur son programme nutrition
  // (détail du programme volontairement hors de ce dépôt public — voir
  // CLAUDE.md § Sécurité et vie privée). Ajoutées créneau par créneau, validées
  // une par une avant intégration ; le catalogue "grand public" ci-dessus sera
  // retiré une fois tous les créneaux couverts par ses propres recettes. ---
  {
    id: "rituel-du-reveil",
    nom: "Rituel du réveil",
    repas: "Petit-déjeuner",
    materiel: [],
    tempsPreparation: 2,
    tempsCuisson: 0,
    portionsReference: 1,
    etapes: "1. À jeun, avant le petit-déjeuner : bois un verre d'eau assis, en 3 gorgées, jamais glacée.\n2. Mange 3 dattes.\n3. Prends 1 c. à café de miel.\n4. Termine avec une pincée de graines de nigelle.",
    etiquettes: ["sain", "rapide-a-preparer", "vegetalien", "sans-gluten", "sans-lactose", "economique"],
    ingredients: [
      { ingredientId: "dattes", quantitePortion: 3, unite: "pièce" },
      { ingredientId: "miel", quantitePortion: 1, unite: "c. à café" },
      { ingredientId: "graines-de-nigelle", quantitePortion: 1, unite: "g" },
    ],
  },
  {
    id: "3-oeufs-avocat",
    nom: "3 œufs & avocat",
    repas: "Petit-déjeuner",
    materiel: ["Poêle"],
    tempsPreparation: 3,
    tempsCuisson: 5,
    portionsReference: 1,
    etapes: "1. Poêle, 1 c. à café d'huile d'olive, feu moyen. Casse 3 œufs : au plat (couvert, 3–4 min) ou brouillés (2–3 min en remuant).\n2. Coupe l'avocat, garde la moitié avec le noyau au frigo, tranche l'autre.\n3. Sel, poivre.",
    etiquettes: ["sain", "rapide-a-preparer", "vegetarien", "sans-gluten", "sans-lactose", "riche-en-proteines"],
    ingredients: [
      { ingredientId: "oeufs", quantitePortion: 3, unite: "pièce" },
      { ingredientId: "avocat", quantitePortion: 0.5, unite: "pièce" },
      { ingredientId: "huile-d-olive", quantitePortion: 1, unite: "c. à café" },
      { ingredientId: "sel", quantitePortion: 0.5, unite: "g" },
      { ingredientId: "poivre", quantitePortion: 0.5, unite: "g" },
    ],
  },
  {
    id: "bol-yaourt-grec-fruits-rouges",
    nom: "Bol yaourt grec aux fruits rouges",
    repas: "Petit-déjeuner",
    materiel: [],
    tempsPreparation: 2,
    tempsCuisson: 0,
    portionsReference: 1,
    etapes: "1. Verse 200 g de yaourt grec dans un bol.\n2. Ajoute une grosse poignée de fruits rouges.\n3. Concasse grossièrement une poignée de noix et d'amandes dans ta main et parsème.\n4. Filet de miel si tu veux.",
    etiquettes: ["sain", "rapide-a-preparer", "vegetarien", "sans-gluten", "riche-en-proteines"],
    ingredients: [
      { ingredientId: "yaourt-grec-nature", quantitePortion: 200, unite: "g" },
      { ingredientId: "fruits-rouges", quantitePortion: 80, unite: "g" },
      { ingredientId: "noix-et-amandes", quantitePortion: 30, unite: "g" },
      { ingredientId: "miel", quantitePortion: 1, unite: "c. à café" },
    ],
  },
];
