// Ma Semaine — données de base : catalogue des ingrédients et des plats.
//
// Origine : reprises telles quelles depuis le Notion de Qassim (bases
// "🧺 Ingrédients" et "📖 Mes plats & repas"), voir CLAUDE.md § Données existantes.
// Les quantités par portion viennent de la base "🧾 Composition des plats"
// (déjà calculées là-bas en divisant la recette totale par son nombre de portions).
//
// Ce fichier ne contient QUE des données statiques (aucune fonction de calcul :
// ça, c'est le rôle de calculs.js, à l'étape suivante).

// --- Catalogue des ingrédients ---
// unite : l'unité dans laquelle le stock de cet ingrédient est compté.
// parCuillereACafe : pour les ingrédients dosés en cuillères dans les recettes,
//   la quantité (dans "unite") que représente 1 c. à café. null si non concerné.
//   1 c. à soupe = 3 c. à café (conversion utilisée par calculs.js).
export const ingredients = [
  {
    id: "paprika",
    nom: "Paprika",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 2.5,
  },
  {
    id: "banane",
    nom: "Banane",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "huile-d-olive",
    nom: "Huile d'olive",
    rayon: "Épicerie salée",
    unite: "ml",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "pois-chiches",
    nom: "Pois chiches",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "bouillon-de-volaille-halal",
    nom: "Bouillon de volaille halal",
    rayon: "Épicerie salée",
    unite: "cube",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pouch-skyr-15-g-de-proteines",
    nom: "Pouch skyr (≈ 15 g de protéines)",
    rayon: "Crèmerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "feta-de-brebis",
    nom: "Feta de brebis",
    rayon: "Crèmerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "epinards",
    nom: "Épinards",
    rayon: "Surgelés",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "tomates",
    nom: "Tomates",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "citron",
    nom: "Citron",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "dattes",
    nom: "Dattes",
    rayon: "Épicerie sucrée",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "ail",
    nom: "Ail",
    rayon: "Fruits et légumes",
    unite: "gousse",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "tomates-cerises",
    nom: "Tomates cerises",
    rayon: "Fruits et légumes",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "beurre-de-cacahuete-100-arachide",
    nom: "Beurre de cacahuète 100% arachide",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "roquette",
    nom: "Roquette",
    rayon: "Fruits et légumes",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "riz",
    nom: "Riz",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "graines-de-chia",
    nom: "Graines de chia",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 4,
  },
  {
    id: "patate-douce",
    nom: "Patate douce",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pates-spaghetti",
    nom: "Pâtes (spaghetti)",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "orge-perle",
    nom: "Orge perlé",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "blettes",
    nom: "Blettes",
    rayon: "Fruits et légumes",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "fruits-rouges",
    nom: "Fruits rouges",
    rayon: "Surgelés",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "poivron",
    nom: "Poivron",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "poivre",
    nom: "Poivre",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 2.5,
  },
  {
    id: "cafe",
    nom: "Café",
    rayon: "Boissons",
    unite: "dose",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "citron-vert",
    nom: "Citron vert",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "concombre",
    nom: "Concombre",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "oignon-rouge",
    nom: "Oignon rouge",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "poulet-hache",
    nom: "Poulet haché",
    rayon: "Boucherie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "cumin",
    nom: "Cumin",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 2.5,
  },
  {
    id: "raisin",
    nom: "Raisin",
    rayon: "Fruits et légumes",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "lentilles",
    nom: "Lentilles",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pave-de-saumon",
    nom: "Pavé de saumon",
    rayon: "Poissonnerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "concentre-de-tomate",
    nom: "Concentré de tomate",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5.3,
  },
  {
    id: "sel",
    nom: "Sel",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 6,
  },
  {
    id: "tomates-concassees",
    nom: "Tomates concassées",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "poulet-morceaux-filet-cuisse-pilon",
    nom: "Poulet (morceaux : filet/cuisse/pilon)",
    rayon: "Boucherie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pain-complet-au-levain",
    nom: "Pain complet au levain",
    rayon: "Boulangerie",
    unite: "tranche",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "oignon",
    nom: "Oignon",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "yaourt-grec-nature",
    nom: "Yaourt grec nature",
    rayon: "Crèmerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "salade",
    nom: "Salade",
    rayon: "Fruits et légumes",
    unite: "poignée",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "miel",
    nom: "Miel",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 7,
  },
  {
    id: "haricots-rouges-ou-noirs",
    nom: "Haricots rouges (ou noirs)",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "flocons-d-avoine",
    nom: "Flocons d'avoine",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "avocat",
    nom: "Avocat",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "noix-et-amandes",
    nom: "Noix et amandes",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "houmous",
    nom: "Houmous",
    rayon: "Crèmerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "poisson-en-boite-thon-sardines-maquereau",
    nom: "Poisson en boîte (thon/sardines/maquereau)",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "potiron",
    nom: "Potiron",
    rayon: "Fruits et légumes",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "oeufs",
    nom: "Œufs",
    rayon: "Crèmerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "ail-en-poudre",
    nom: "Ail en poudre",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 3,
  },
  // --- Ajoutés depuis la liste de courses Apple Rappels de Qassim ---
  // Aucun n'est utilisé par un plat pour l'instant : ils ne profitent du
  // mécanisme "essentiel + minimum" qu'une fois réglé dans l'écran Stock.
  {
    id: "curcuma",
    nom: "Curcuma",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "gingembre-moulu",
    nom: "Gingembre moulu",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "graines-de-nigelle",
    nom: "Graines de nigelle (Black seed)",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "fromage-rape",
    nom: "Fromage râpé",
    rayon: "Crèmerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  // --- Compléments alimentaires (nouveau rayon) ---
  {
    id: "zinc-bisglycinate",
    nom: "Zinc bisglycinate",
    rayon: "Compléments alimentaires",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "omega-3",
    nom: "Oméga 3",
    rayon: "Compléments alimentaires",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "vitamine-d-vitamine-k2",
    nom: "Vitamine D + vitamine K2",
    rayon: "Compléments alimentaires",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "magnesium-bisglycinate",
    nom: "Magnésium bisglycinate",
    rayon: "Compléments alimentaires",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "persil",
    nom: "Persil",
    rayon: "Fruits et légumes",
    unite: "bouquet",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "coriandre",
    nom: "Coriandre",
    rayon: "Fruits et légumes",
    unite: "bouquet",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "fromage-de-chevre",
    nom: "Fromage de chèvre",
    rayon: "Crèmerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "fromage-de-brebis",
    nom: "Fromage de brebis",
    rayon: "Crèmerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "boeuf-hache",
    nom: "Bœuf haché",
    rayon: "Boucherie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "agneau-hache",
    nom: "Agneau haché",
    rayon: "Boucherie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "parmesan-rape",
    nom: "Parmesan râpé",
    rayon: "Crèmerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pecorino-rape",
    nom: "Pecorino râpé",
    rayon: "Crèmerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "bacon-de-boeuf",
    nom: "Bacon de bœuf",
    rayon: "Boucherie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "bacon-de-dinde",
    nom: "Bacon de dinde",
    rayon: "Boucherie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "wraps-complets",
    nom: "Wraps complets",
    rayon: "Épicerie salée",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pain-pita",
    nom: "Pain pita",
    rayon: "Boulangerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "boeuf-faux-filet",
    nom: "Bœuf faux-filet",
    rayon: "Boucherie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "boeuf-en-cubes",
    nom: "Bœuf en cubes",
    rayon: "Boucherie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "chili-en-poudre",
    nom: "Chili en poudre",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 2.5,
  },
  {
    id: "piment-doux",
    nom: "Piment doux",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 2.5,
  },
  {
    id: "lait",
    nom: "Lait",
    rayon: "Crèmerie",
    unite: "ml",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "kefir",
    nom: "Kéfir",
    rayon: "Crèmerie",
    unite: "ml",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "carotte",
    nom: "Carotte",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "courgette",
    nom: "Courgette",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "poireau",
    nom: "Poireau",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "champignons-de-paris",
    nom: "Champignons de Paris",
    rayon: "Fruits et légumes",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pomme-de-terre",
    nom: "Pomme de terre",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pomme",
    nom: "Pomme",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "orange",
    nom: "Orange",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "brocoli",
    nom: "Brocoli",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "merguez-halal",
    nom: "Merguez (halal)",
    rayon: "Boucherie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "escalope-de-dinde",
    nom: "Escalope de dinde",
    rayon: "Boucherie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "saucisses-de-volaille-halal",
    nom: "Saucisses de volaille (halal)",
    rayon: "Boucherie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "cabillaud",
    nom: "Cabillaud",
    rayon: "Poissonnerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "crevettes",
    nom: "Crevettes",
    rayon: "Poissonnerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "thon-frais",
    nom: "Thon frais",
    rayon: "Poissonnerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "sole",
    nom: "Sole",
    rayon: "Poissonnerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "dorade",
    nom: "Dorade",
    rayon: "Poissonnerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "moules",
    nom: "Moules",
    rayon: "Poissonnerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "calamars",
    nom: "Calamars",
    rayon: "Poissonnerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "saumon-fume",
    nom: "Saumon fumé",
    rayon: "Poissonnerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "merlan",
    nom: "Merlan",
    rayon: "Poissonnerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "beurre",
    nom: "Beurre",
    rayon: "Crèmerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "creme-fraiche",
    nom: "Crème fraîche",
    rayon: "Crèmerie",
    unite: "ml",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "mozzarella",
    nom: "Mozzarella",
    rayon: "Crèmerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "baguette",
    nom: "Baguette",
    rayon: "Boulangerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pain-de-mie",
    nom: "Pain de mie",
    rayon: "Boulangerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "croissant",
    nom: "Croissant",
    rayon: "Boulangerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "brioche",
    nom: "Brioche",
    rayon: "Boulangerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "naan",
    nom: "Naan",
    rayon: "Boulangerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "petits-pains",
    nom: "Petits pains",
    rayon: "Boulangerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pain-aux-cereales",
    nom: "Pain aux céréales",
    rayon: "Boulangerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "biscottes",
    nom: "Biscottes",
    rayon: "Boulangerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "farine",
    nom: "Farine",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "sauce-soja",
    nom: "Sauce soja",
    rayon: "Épicerie salée",
    unite: "ml",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "moutarde",
    nom: "Moutarde",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "mayonnaise",
    nom: "Mayonnaise",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "vinaigre",
    nom: "Vinaigre",
    rayon: "Épicerie salée",
    unite: "ml",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "semoule",
    nom: "Semoule",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "quinoa",
    nom: "Quinoa",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "sauce-tomate",
    nom: "Sauce tomate",
    rayon: "Épicerie salée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "sucre",
    nom: "Sucre",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 4,
  },
  {
    id: "confiture",
    nom: "Confiture",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "pate-a-tartiner",
    nom: "Pâte à tartiner",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "chocolat-en-poudre",
    nom: "Chocolat en poudre",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 3,
  },
  {
    id: "cereales",
    nom: "Céréales",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "biscuits",
    nom: "Biscuits",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "levure-chimique",
    nom: "Levure chimique",
    rayon: "Épicerie sucrée",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 3,
  },
  {
    id: "sirop-d-erable",
    nom: "Sirop d'érable",
    rayon: "Épicerie sucrée",
    unite: "ml",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "cannelle",
    nom: "Cannelle",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 2.5,
  },
  {
    id: "muscade",
    nom: "Muscade",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 2,
  },
  {
    id: "herbes-de-provence",
    nom: "Herbes de Provence",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 1.5,
  },
  {
    id: "origan",
    nom: "Origan",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 1.5,
  },
  {
    id: "thym",
    nom: "Thym",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 1.5,
  },
  {
    id: "laurier",
    nom: "Laurier",
    rayon: "Épices et condiments",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 1,
  },
  {
    id: "legumes-surgeles-melanges",
    nom: "Légumes surgelés mélangés",
    rayon: "Surgelés",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "frites-surgelees",
    nom: "Frites surgelées",
    rayon: "Surgelés",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "petits-pois-surgeles",
    nom: "Petits pois surgelés",
    rayon: "Surgelés",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "poisson-pane",
    nom: "Poisson pané",
    rayon: "Surgelés",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "glace",
    nom: "Glace",
    rayon: "Surgelés",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pizza-surgelee",
    nom: "Pizza surgelée",
    rayon: "Surgelés",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "eau-minerale",
    nom: "Eau minérale",
    rayon: "Boissons",
    unite: "ml",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "jus-d-orange",
    nom: "Jus d'orange",
    rayon: "Boissons",
    unite: "ml",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "the",
    nom: "Thé",
    rayon: "Boissons",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "soda",
    nom: "Soda",
    rayon: "Boissons",
    unite: "ml",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "sirop",
    nom: "Sirop",
    rayon: "Boissons",
    unite: "ml",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "whey-proteine",
    nom: "Whey protéine",
    rayon: "Compléments alimentaires",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "multivitamines",
    nom: "Multivitamines",
    rayon: "Compléments alimentaires",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "dentifrice",
    nom: "Dentifrice",
    rayon: "Hygiène",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "brosse-a-dents",
    nom: "Brosse à dents",
    rayon: "Hygiène",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "deodorant",
    nom: "Déodorant",
    rayon: "Hygiène",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "gel-douche",
    nom: "Gel douche",
    rayon: "Hygiène",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "shampoing",
    nom: "Shampoing",
    rayon: "Hygiène",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "savon",
    nom: "Savon",
    rayon: "Hygiène",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "papier-toilette",
    nom: "Papier toilette",
    rayon: "Hygiène",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "rasoir",
    nom: "Rasoir",
    rayon: "Hygiène",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "coton-tiges",
    nom: "Coton-tiges",
    rayon: "Hygiène",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "protections-hygieniques",
    nom: "Protections hygiéniques",
    rayon: "Hygiène",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "liquide-vaisselle",
    nom: "Liquide vaisselle",
    rayon: "Entretien maison",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "lessive",
    nom: "Lessive",
    rayon: "Entretien maison",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "adoucissant",
    nom: "Adoucissant",
    rayon: "Entretien maison",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "eau-de-javel",
    nom: "Eau de Javel",
    rayon: "Entretien maison",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "nettoyant-multi-usage",
    nom: "Nettoyant multi-usage",
    rayon: "Entretien maison",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "sacs-poubelle",
    nom: "Sacs poubelle",
    rayon: "Entretien maison",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "essuie-tout",
    nom: "Essuie-tout",
    rayon: "Entretien maison",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "anti-calcaire",
    nom: "Anti-calcaire",
    rayon: "Entretien maison",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "eponges",
    nom: "Éponges",
    rayon: "Entretien maison",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "gants-menagers",
    nom: "Gants ménagers",
    rayon: "Entretien maison",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "film-alimentaire",
    nom: "Film alimentaire",
    rayon: "Emballage",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "papier-aluminium",
    nom: "Papier aluminium",
    rayon: "Emballage",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "sacs-congelation",
    nom: "Sacs congélation",
    rayon: "Emballage",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "papier-cuisson",
    nom: "Papier cuisson",
    rayon: "Emballage",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "boites-de-conservation",
    nom: "Boîtes de conservation",
    rayon: "Emballage",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
];

// --- Catalogue des plats ---
// repas : un des 7 repères Notion d'origine ("Petit-déjeuner", "Smoko", "Déjeuner",
//   "Snack", "Dîner", "Préparation de base", "Plaisir occasionnel"). Les 5 premiers
//   correspondent aux créneaux de l'écran Semaine ; les 2 derniers sont des plats
//   à part (base à préparer, ou écart occasionnel) non rattachés à un créneau fixe.
// assemblage : true si le plat ne demande aucune cuisson (juste assembler).
// portionsReference : nombre de portions de la recette d'origine (indicatif).
// ingredients[].quantitePortion : quantité nécessaire pour UNE portion, dans
//   l'unité "unite" de la ligne (peut différer de l'unité de stock : conversion
//   cuillère → unite de stock faite par calculs.js via parCuillereACafe).
export const plats = [
  {
    id: "poulet-patate-douce-epinards",
    nom: "Poulet, patate douce & épinards",
    repas: "Dîner",
    assemblage: false,
    portionsReference: 1,
    etapes: "1. Patate douce. En dés avec la peau, huile, sel. Air fryer 200°C, 18–20 min, secoue à mi-cuisson.\n2. Poulet. En lanières, paprika, sel, poivre. Poêle, 6–8 min. Réserve.\n3. Oignon et ail. Même poêle, 3 min.\n4. Tomate. En dés, 2 min.\n5. Épinards. 2 poignées, 1–2 min, remets le poulet. Sers avec la patate douce.",
    ingredients: [
      { ingredientId: "oignon", quantitePortion: 0.5, unite: "pièce" },
      { ingredientId: "tomates", quantitePortion: 1, unite: "pièce" },
      { ingredientId: "sel", quantitePortion: 1, unite: "g" },
      { ingredientId: "huile-d-olive", quantitePortion: 1, unite: "c. à soupe" },
      { ingredientId: "poulet-morceaux-filet-cuisse-pilon", quantitePortion: 175, unite: "g" },
      { ingredientId: "ail", quantitePortion: 1, unite: "gousse" },
      { ingredientId: "paprika", quantitePortion: 1, unite: "g" },
      { ingredientId: "epinards", quantitePortion: 60, unite: "g" },
      { ingredientId: "patate-douce", quantitePortion: 1, unite: "pièce" },
      { ingredientId: "poivre", quantitePortion: 1, unite: "g" },
    ],
  },
  {
    id: "oeufs-avocat-pain-au-levain",
    nom: "Œufs, avocat & pain au levain",
    repas: "Petit-déjeuner",
    assemblage: false,
    portionsReference: 1,
    etapes: "1. Pain. Fais griller 1–2 tranches de pain dans la poêle sèche, 1–2 min par face. Réserve.\n2. Œufs. Mets 1 c. à café d'huile d'olive dans la poêle, feu moyen. Casse 3 œufs. Au plat : couvre, 3–4 min. Brouillés : bats-les avant, remue sans arrêt 2–3 min à feu doux.\n3. Avocat. Coupe l'avocat en deux, garde la moitié avec le noyau au frigo, tranche l'autre.\n4. Service. Sel, poivre, une poignée de noix et d'amandes à côté.\nVariante sans cuisson : 3 œufs durs à la place des œufs cuits.",
    ingredients: [
      { ingredientId: "oeufs", quantitePortion: 3, unite: "pièce" },
      { ingredientId: "avocat", quantitePortion: 0.5, unite: "pièce" },
      { ingredientId: "sel", quantitePortion: 1, unite: "g" },
      { ingredientId: "poivre", quantitePortion: 1, unite: "g" },
      { ingredientId: "pain-complet-au-levain", quantitePortion: 1.5, unite: "tranche" },
      { ingredientId: "noix-et-amandes", quantitePortion: 30, unite: "g" },
      { ingredientId: "huile-d-olive", quantitePortion: 1, unite: "c. à café" },
    ],
  },
  {
    id: "salade-de-lentilles",
    nom: "Salade de lentilles",
    repas: "Déjeuner",
    assemblage: false,
    portionsReference: 3,
    etapes: "1. Égoutte, rince les lentilles.\n2. Concombre en dés, tomates en dés, oignon rouge et persil hachés.\n3. Émiette 100 g de feta.\n4. Assaisonne : huile, citron, cumin, sel, poivre. 3 boîtes, frigo 3 jours.\nPour un déjeuner complet : ajoute 2 œufs durs ou une boîte de sardines, et du pain au levain.",
    ingredients: [
      { ingredientId: "citron", quantitePortion: 0.33, unite: "pièce" },
      { ingredientId: "feta-de-brebis", quantitePortion: 33.3, unite: "g" },
      { ingredientId: "poivre", quantitePortion: 0.17, unite: "c. à café" },
      { ingredientId: "oignon-rouge", quantitePortion: 0.17, unite: "pièce" },
      { ingredientId: "cumin", quantitePortion: 0.17, unite: "c. à café" },
      { ingredientId: "lentilles", quantitePortion: 266.7, unite: "g" },
      { ingredientId: "huile-d-olive", quantitePortion: 1, unite: "c. à soupe" },
      { ingredientId: "tomates", quantitePortion: 0.67, unite: "pièce" },
      { ingredientId: "sel", quantitePortion: 0.17, unite: "c. à café" },
      { ingredientId: "persil", quantitePortion: 0.17, unite: "bouquet" },
      { ingredientId: "concombre", quantitePortion: 0.33, unite: "pièce" },
    ],
  },
  {
    id: "bol-yaourt-grec",
    nom: "Bol yaourt grec",
    repas: "Petit-déjeuner",
    assemblage: false,
    portionsReference: 1,
    etapes: "1. Verse 200 g de yaourt grec dans un bol.\n2. Ajoute une grosse poignée de fruits rouges.\n3. Concasse grossièrement une poignée de noix et d'amandes dans ta main et parsème.\n4. Filet de miel si tu veux. Pain au levain à côté si tu as encore faim.\nAstuce : des fruits rouges surgelés, mis au frigo la veille, sont décongelés le matin.",
    ingredients: [
      { ingredientId: "miel", quantitePortion: 1, unite: "c. à café" },
      { ingredientId: "yaourt-grec-nature", quantitePortion: 200, unite: "g" },
      { ingredientId: "fruits-rouges", quantitePortion: 80, unite: "g" },
      { ingredientId: "noix-et-amandes", quantitePortion: 30, unite: "g" },
    ],
  },
  {
    id: "avoine-trempee",
    nom: "Avoine trempée",
    repas: "Petit-déjeuner",
    assemblage: true,
    portionsReference: 1,
    etapes: "1. La veille. Dans un pot, mélange 50 g de flocons d'avoine, 150 ml de lait, 2 c. à soupe de yaourt grec et 1 c. à soupe de chia. Ferme, frigo.\n2. Le matin. Ajoute une poignée de fruits rouges. Miel facultatif.",
    ingredients: [
      { ingredientId: "yaourt-grec-nature", quantitePortion: 2, unite: "c. à soupe" },
      { ingredientId: "flocons-d-avoine", quantitePortion: 50, unite: "g" },
      { ingredientId: "fruits-rouges", quantitePortion: 80, unite: "g" },
      { ingredientId: "graines-de-chia", quantitePortion: 1, unite: "c. à soupe" },
      { ingredientId: "lait", quantitePortion: 150, unite: "ml" },
    ],
  },
  {
    id: "oeufs-brouilles-guacamole-pain",
    nom: "Œufs brouillés, guacamole & pain",
    repas: "Petit-déjeuner",
    assemblage: false,
    portionsReference: 1,
    etapes: "1. Guacamole. Écrase ½ avocat à la fourchette avec sel, poivre et cumin.\n2. Étale le guacamole sur une tranche de pain.\n3. Œufs. Huile d'olive dans la poêle, feu doux. Bats 3 œufs, verse, remue 2–3 min (brouillés).\n4. Dépose les œufs brouillés sur le pain.",
    ingredients: [
      { ingredientId: "oeufs", quantitePortion: 3, unite: "pièce" },
      { ingredientId: "avocat", quantitePortion: 0.5, unite: "pièce" },
      { ingredientId: "sel", quantitePortion: 1, unite: "g" },
      { ingredientId: "poivre", quantitePortion: 1, unite: "g" },
      { ingredientId: "cumin", quantitePortion: 1, unite: "g" },
      { ingredientId: "pain-complet-au-levain", quantitePortion: 1, unite: "tranche" },
      { ingredientId: "huile-d-olive", quantitePortion: 1, unite: "c. à café" },
    ],
  },
];

