// Ma Semaine — données de base : catalogue des ingrédients et des plats.
//
// Origine : reprises telles quelles depuis le Notion de Qassim (bases
// "🧺 Ingrédients" et "📖 Mes plats & repas"), voir CLAUDE.md § Données existantes.
// Les quantités par portion viennent de la base "🧾 Composition des plats"
// (déjà calculées là-bas en divisant la recette totale par son nombre de portions).
//
// Ce fichier ne contient QUE des données statiques (aucune fonction de calcul :
// ça, c'est le rôle de calculs.js, à l'étape suivante).

// --- Catalogue des ingrédients ---
// unite : l'unité dans laquelle le stock de cet ingrédient est compté.
// parCuillereACafe : pour les ingrédients dosés en cuillères dans les recettes,
//   la quantité (dans "unite") que représente 1 c. à café. null si non concerné.
//   1 c. à soupe = 3 c. à café (conversion utilisée par calculs.js).
export const ingredients = [
  {
    id: "paprika",
    nom: "Paprika",
    rayon: "Épices",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 2.5,
  },
  {
    id: "banane",
    nom: "Banane",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "huile-d-olive",
    nom: "Huile d'olive",
    rayon: "Épicerie",
    unite: "ml",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "fromage-de-brebis-ou-de-chevre",
    nom: "Fromage de brebis ou de chèvre",
    rayon: "Crèmerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pois-chiches",
    nom: "Pois chiches",
    rayon: "Conserves",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "boeuf-ou-agneau-hache",
    nom: "Bœuf ou agneau haché",
    rayon: "Boucherie halal",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "bouillon-de-volaille-halal",
    nom: "Bouillon de volaille halal",
    rayon: "Épicerie",
    unite: "cube",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pouch-skyr-15-g-de-proteines",
    nom: "Pouch skyr (≈ 15 g de protéines)",
    rayon: "Crèmerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "feta-de-brebis",
    nom: "Feta de brebis",
    rayon: "Crèmerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "persil-ou-coriandre",
    nom: "Persil ou coriandre",
    rayon: "Fruits et légumes",
    unite: "bouquet",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "epinards",
    nom: "Épinards",
    rayon: "Surgelés ou frais",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "tomates",
    nom: "Tomates",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "citron",
    nom: "Citron",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "dattes",
    nom: "Dattes",
    rayon: "Épicerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "parmesan-ou-pecorino-rape",
    nom: "Parmesan ou pecorino râpé",
    rayon: "Crèmerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "ail",
    nom: "Ail",
    rayon: "Fruits et légumes",
    unite: "gousse",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "tomates-cerises",
    nom: "Tomates cerises",
    rayon: "Fruits et légumes",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "beurre-de-cacahuete-100-arachide",
    nom: "Beurre de cacahuète 100% arachide",
    rayon: "Épicerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "roquette",
    nom: "Roquette",
    rayon: "Fruits et légumes",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "riz",
    nom: "Riz",
    rayon: "Épicerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "graines-de-chia",
    nom: "Graines de chia",
    rayon: "Épicerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 4,
  },
  {
    id: "patate-douce",
    nom: "Patate douce",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pates-spaghetti",
    nom: "Pâtes (spaghetti)",
    rayon: "Épicerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "orge-perle",
    nom: "Orge perlé",
    rayon: "Épicerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "bacon-de-boeuf-ou-de-dinde",
    nom: "Bacon de bœuf ou de dinde",
    rayon: "Boucherie halal",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "blettes",
    nom: "Blettes",
    rayon: "Fruits et légumes",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "fruits-rouges",
    nom: "Fruits rouges",
    rayon: "Surgelés ou frais",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "poivron",
    nom: "Poivron",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "wraps-complets-ou-pitas",
    nom: "Wraps complets ou pitas",
    rayon: "Épicerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "boeuf-faux-filet-ou-cubes",
    nom: "Bœuf (faux-filet ou cubes)",
    rayon: "Boucherie halal",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "poivre",
    nom: "Poivre",
    rayon: "Épices",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 2.5,
  },
  {
    id: "cafe",
    nom: "Café",
    rayon: "Épicerie",
    unite: "dose",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "citron-vert",
    nom: "Citron vert",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "concombre",
    nom: "Concombre",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "oignon-rouge",
    nom: "Oignon rouge",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "poulet-hache",
    nom: "Poulet haché",
    rayon: "Boucherie halal",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "cumin",
    nom: "Cumin",
    rayon: "Épices",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 2.5,
  },
  {
    id: "raisin",
    nom: "Raisin",
    rayon: "Fruits et légumes",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "lentilles",
    nom: "Lentilles",
    rayon: "Conserves",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "chili-ou-piment-doux",
    nom: "Chili ou piment doux",
    rayon: "Épices",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 2.5,
  },
  {
    id: "pave-de-saumon",
    nom: "Pavé de saumon",
    rayon: "Poissonnerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "lait-ou-kefir",
    nom: "Lait ou kéfir",
    rayon: "Crèmerie",
    unite: "ml",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "concentre-de-tomate",
    nom: "Concentré de tomate",
    rayon: "Conserves",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5.3,
  },
  {
    id: "sel",
    nom: "Sel",
    rayon: "Épices",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 6,
  },
  {
    id: "tomates-concassees",
    nom: "Tomates concassées",
    rayon: "Conserves",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "poulet-morceaux-filet-cuisse-pilon",
    nom: "Poulet (morceaux : filet/cuisse/pilon)",
    rayon: "Boucherie halal",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "pain-complet-au-levain",
    nom: "Pain complet au levain",
    rayon: "Boulangerie",
    unite: "tranche",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "oignon",
    nom: "Oignon",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "yaourt-grec-nature",
    nom: "Yaourt grec nature",
    rayon: "Crèmerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 5,
  },
  {
    id: "salade",
    nom: "Salade",
    rayon: "Fruits et légumes",
    unite: "poignée",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "miel",
    nom: "Miel",
    rayon: "Épicerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 7,
  },
  {
    id: "haricots-rouges-ou-noirs",
    nom: "Haricots rouges (ou noirs)",
    rayon: "Conserves",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "flocons-d-avoine",
    nom: "Flocons d'avoine",
    rayon: "Épicerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "avocat",
    nom: "Avocat",
    rayon: "Fruits et légumes",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "noix-et-amandes",
    nom: "Noix et amandes",
    rayon: "Épicerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "houmous",
    nom: "Houmous",
    rayon: "Crèmerie",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "poisson-en-boite-thon-sardines-maquereau",
    nom: "Poisson en boîte (thon/sardines/maquereau)",
    rayon: "Conserves",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "potiron",
    nom: "Potiron",
    rayon: "Fruits et légumes",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "oeufs",
    nom: "Œufs",
    rayon: "Crèmerie",
    unite: "pièce",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: null,
  },
  {
    id: "ail-en-poudre",
    nom: "Ail en poudre",
    rayon: "Épices",
    unite: "g",
    enStock: 0,
    essentiel: false,
    minimum: 0,
    extra: 0,
    parCuillereACafe: 3,
  },
];

// --- Catalogue des plats ---
// repas : un des 7 repères Notion d'origine ("Petit-déjeuner", "Smoko", "Déjeuner",
//   "Snack", "Dîner", "Préparation de base", "Plaisir occasionnel"). Les 5 premiers
//   correspondent aux créneaux de l'écran Semaine ; les 2 derniers sont des plats
//   à part (base à préparer, ou écart occasionnel) non rattachés à un créneau fixe.
// assemblage : true si le plat ne demande aucune cuisson (juste assembler).
// portionsReference : nombre de portions de la recette d'origine (indicatif).
// ingredients[].quantitePortion : quantité nécessaire pour UNE portion, dans
//   l'unité "unite" de la ligne (peut différer de l'unité de stock : conversion
//   cuillère → unite de stock faite par calculs.js via parCuillereACafe).
export const plats = [
  {
    id: "snack-rapide-banane-miel-pouch",
    nom: "Snack rapide : banane, miel & pouch",
    repas: "Snack",
    assemblage: true,
    portionsReference: 1,
    etapes: "Carburant avant la séance, version express.\n- 1 banane\n- 1 c. à café de miel\n- 1 pouch de skyr",
    ingredients: [
      { ingredientId: "banane", quantitePortion: 1, unite: "pièce" },
      { ingredientId: "miel", quantitePortion: 7, unite: "g" },
      { ingredientId: "pouch-skyr-15-g-de-proteines", quantitePortion: 1, unite: "pièce" },
    ],
  },
  {
    id: "pates-carbonara-halal",
    nom: "Pâtes carbonara (halal)",
    repas: "Plaisir occasionnel",
    assemblage: false,
    portionsReference: 1,
    etapes: "1. Cuis les pâtes à l'eau salée. Garde un demi-verre d'eau de cuisson.\n2. Bacon en lamelles, poêle sans matière grasse, 4–5 min.\n3. Bats œuf + jaunes + fromage + poivre.\n4. Feu coupé, pâtes égoutées dans la poêle, mélange aux œufs et un peu d'eau de cuisson. Remue vite, sans crème.\nPour équilibrer : une grosse salade verte à côté.",
    ingredients: [
      { ingredientId: "oeufs", quantitePortion: 3, unite: "pièce" },
      { ingredientId: "poivre", quantitePortion: 2, unite: "g" },
      { ingredientId: "bacon-de-boeuf-ou-de-dinde", quantitePortion: 80, unite: "g" },
      { ingredientId: "pates-spaghetti", quantitePortion: 100, unite: "g" },
      { ingredientId: "parmesan-ou-pecorino-rape", quantitePortion: 30, unite: "g" },
    ],
  },
  {
    id: "omelette-legumes-sautes",
    nom: "Omelette & légumes sautés",
    repas: "Dîner",
    assemblage: false,
    portionsReference: 1,
    etapes: "1. Oignon 3 min, tomate en dés 2 min, épinards 1 min.\n2. Bats 3–4 œufs, sel, poivre, verse sur les légumes. Couvre, feu doux, 3–4 min.\n3. Émiette le fromage, plie l'omelette. Une tranche de pain au levain.",
    ingredients: [
      { ingredientId: "epinards", quantitePortion: 30, unite: "g" },
      { ingredientId: "huile-d-olive", quantitePortion: 1, unite: "c. à soupe" },
      { ingredientId: "oignon", quantitePortion: 0.5, unite: "pièce" },
      { ingredientId: "tomates", quantitePortion: 1, unite: "pièce" },
      { ingredientId: "fromage-de-brebis-ou-de-chevre", quantitePortion: 30, unite: "g" },
      { ingredientId: "oeufs", quantitePortion: 3.5, unite: "pièce" },
      { ingredientId: "pain-complet-au-levain", quantitePortion: 1, unite: "tranche" },
    ],
  },
  {
    id: "snack-leger-yaourt-grec-fruits-rouges",
    nom: "Snack léger : yaourt grec & fruits rouges",
    repas: "Snack",
    assemblage: true,
    portionsReference: 1,
    etapes: "Avant la séance, quand tu n'as pas très faim.\n- 150 g de yaourt grec nature\n- Quelques fruits rouges (≈ 80 g)",
    ingredients: [
      { ingredientId: "yaourt-grec-nature", quantitePortion: 150, unite: "g" },
      { ingredientId: "fruits-rouges", quantitePortion: 80, unite: "g" },
    ],
  },
  {
    id: "poulet-patate-douce-epinards",
    nom: "Poulet, patate douce & épinards",
    repas: "Dîner",
    assemblage: false,
    portionsReference: 1,
    etapes: "1. Patate douce. En dés avec la peau, huile, sel. Air fryer 200°C, 18–20 min, secoue à mi-cuisson.\n2. Poulet. En lanières, paprika, sel, poivre. Poêle, 6–8 min. Réserve.\n3. Oignon et ail. Même poêle, 3 min.\n4. Tomate. En dés, 2 min.\n5. Épinards. 2 poignées, 1–2 min, remets le poulet. Sers avec la patate douce.",
    ingredients: [
      { ingredientId: "oignon", quantitePortion: 0.5, unite: "pièce" },
      { ingredientId: "tomates", quantitePortion: 1, unite: "pièce" },
      { ingredientId: "sel", quantitePortion: 1, unite: "g" },
      { ingredientId: "huile-d-olive", quantitePortion: 1, unite: "c. à soupe" },
      { ingredientId: "poulet-morceaux-filet-cuisse-pilon", quantitePortion: 175, unite: "g" },
      { ingredientId: "ail", quantitePortion: 1, unite: "gousse" },
      { ingredientId: "paprika", quantitePortion: 1, unite: "g" },
      { ingredientId: "epinards", quantitePortion: 60, unite: "g" },
      { ingredientId: "patate-douce", quantitePortion: 1, unite: "pièce" },
      { ingredientId: "poivre", quantitePortion: 1, unite: "g" },
    ],
  },
  {
    id: "oeufs-durs-du-dimanche",
    nom: "Œufs durs du dimanche",
    repas: "Préparation de base",
    assemblage: false,
    portionsReference: 9,
    etapes: "1. Porte une casserole d'eau à ébullition.\n2. Plonge les œufs délicatement avec une cuillère. 10 min.\n3. Passe-les sous l'eau froide 2–3 min.\n4. Range-les dans leur coquille au frigo : jusqu'à 1 semaine.",
    ingredients: [
      { ingredientId: "oeufs", quantitePortion: 1, unite: "pièce" },
    ],
  },
  {
    id: "oeufs-avocat-pain-au-levain",
    nom: "Œufs, avocat & pain au levain",
    repas: "Petit-déjeuner",
    assemblage: false,
    portionsReference: 1,
    etapes: "1. Pain. Fais griller 1–2 tranches de pain dans la poêle sèche, 1–2 min par face. Réserve.\n2. Œufs. Mets 1 c. à café d'huile d'olive dans la poêle, feu moyen. Casse 3 œufs. Au plat : couvre, 3–4 min. Brouillés : bats-les avant, remue sans arrêt 2–3 min à feu doux.\n3. Avocat. Coupe l'avocat en deux, garde la moitié avec le noyau au frigo, tranche l'autre.\n4. Service. Sel, poivre, une poignée de noix et d'amandes à côté.\nVariante sans cuisson : 3 œufs durs à la place des œufs cuits.",
    ingredients: [
      { ingredientId: "oeufs", quantitePortion: 3, unite: "pièce" },
      { ingredientId: "avocat", quantitePortion: 0.5, unite: "pièce" },
      { ingredientId: "sel", quantitePortion: 1, unite: "g" },
      { ingredientId: "poivre", quantitePortion: 1, unite: "g" },
      { ingredientId: "pain-complet-au-levain", quantitePortion: 1.5, unite: "tranche" },
      { ingredientId: "noix-et-amandes", quantitePortion: 30, unite: "g" },
      { ingredientId: "huile-d-olive", quantitePortion: 1, unite: "c. à café" },
    ],
  },
  {
    id: "smoko-copieux-tartines-beurre-de-cacahuete-miel-pouch",
    nom: "Smoko copieux : tartines beurre de cacahuète & miel + pouch",
    repas: "Smoko",
    assemblage: true,
    portionsReference: 1,
    etapes: "Pour les jours où tu as plus faim.\n- 1 café\n- 2 tranches de pain au levain (60–80 g)\n- 2 grosses c. à soupe de beurre de cacahuète 100% arachide (≈ 30 g)\n- 1 c. à café de miel par-dessus\n- 1 pouch de skyr\nÀ préparer le matin et emporter dans le sac réfrigéré.",
    ingredients: [
      { ingredientId: "cafe", quantitePortion: 1, unite: "dose" },
      { ingredientId: "beurre-de-cacahuete-100-arachide", quantitePortion: 30, unite: "g" },
      { ingredientId: "pouch-skyr-15-g-de-proteines", quantitePortion: 1, unite: "pièce" },
      { ingredientId: "pain-complet-au-levain", quantitePortion: 2, unite: "tranche" },
      { ingredientId: "miel", quantitePortion: 7, unite: "g" },
    ],
  },
  {
    id: "pates-a-l-ail-huile-d-olive",
    nom: "Pâtes à l'ail & huile d'olive",
    repas: "Plaisir occasionnel",
    assemblage: false,
    portionsReference: 1,
    etapes: "1. Cuis les pâtes, garde un peu d'eau de cuisson.\n2. Ail émincé, feu doux, huile, piment, 2–3 min sans colorer.\n3. Ajoute les pâtes, l'eau de cuisson, le persil haché.\n4. Ajoute le thon ou les sardines émiettés : sans eux, c'est un accompagnement, pas un repas.",
    ingredients: [
      { ingredientId: "chili-ou-piment-doux", quantitePortion: 1, unite: "g" },
      { ingredientId: "sel", quantitePortion: 1, unite: "g" },
      { ingredientId: "huile-d-olive", quantitePortion: 2, unite: "c. à soupe" },
      { ingredientId: "ail", quantitePortion: 3, unite: "gousse" },
      { ingredientId: "persil-ou-coriandre", quantitePortion: 0.25, unite: "bouquet" },
      { ingredientId: "poisson-en-boite-thon-sardines-maquereau", quantitePortion: 120, unite: "g" },
      { ingredientId: "pates-spaghetti", quantitePortion: 100, unite: "g" },
    ],
  },
  {
    id: "smoko-rapide-cafe-pouch-raisin",
    nom: "Smoko rapide : café, pouch & raisin",
    repas: "Smoko",
    assemblage: true,
    portionsReference: 1,
    etapes: "Le smoko de tous les jours, sans préparation.\n- 1 café\n- 1 pouch de skyr (≈ 15 g de protéines)\n- 1 grosse poignée de raisin (≈ 150 g)",
    ingredients: [
      { ingredientId: "cafe", quantitePortion: 1, unite: "dose" },
      { ingredientId: "raisin", quantitePortion: 150, unite: "g" },
      { ingredientId: "pouch-skyr-15-g-de-proteines", quantitePortion: 1, unite: "pièce" },
    ],
  },
  {
    id: "salade-de-lentilles",
    nom: "Salade de lentilles",
    repas: "Déjeuner",
    assemblage: false,
    portionsReference: 3,
    etapes: "1. Égoutte, rince les lentilles.\n2. Concombre en dés, tomates en dés, oignon rouge et persil hachés.\n3. Émiette 100 g de feta.\n4. Assaisonne : huile, citron, cumin, sel, poivre. 3 boîtes, frigo 3 jours.\nPour un déjeuner complet : ajoute 2 œufs durs ou une boîte de sardines, et du pain au levain.",
    ingredients: [
      { ingredientId: "citron", quantitePortion: 0.33, unite: "pièce" },
      { ingredientId: "feta-de-brebis", quantitePortion: 33.3, unite: "g" },
      { ingredientId: "poivre", quantitePortion: 0.17, unite: "c. à café" },
      { ingredientId: "oignon-rouge", quantitePortion: 0.17, unite: "pièce" },
      { ingredientId: "cumin", quantitePortion: 0.17, unite: "c. à café" },
      { ingredientId: "lentilles", quantitePortion: 266.7, unite: "g" },
      { ingredientId: "huile-d-olive", quantitePortion: 1, unite: "c. à soupe" },
      { ingredientId: "tomates", quantitePortion: 0.67, unite: "pièce" },
      { ingredientId: "sel", quantitePortion: 0.17, unite: "c. à café" },
      { ingredientId: "persil-ou-coriandre", quantitePortion: 0.17, unite: "bouquet" },
      { ingredientId: "concombre", quantitePortion: 0.33, unite: "pièce" },
    ],
  },
  {
    id: "snack-jour-de-repos-yaourt-fruits-rouges-noix",
    nom: "Snack jour de repos : yaourt, fruits rouges & noix",
    repas: "Snack",
    assemblage: true,
    portionsReference: 1,
    etapes: "Mercredi et week-end : en-cas protéiné, sans sucres rapides.\n- 150 g de yaourt grec nature\n- Fruits rouges (≈ 80 g)\n- 1 poignée de noix (≈ 30 g)",
    ingredients: [
      { ingredientId: "noix-et-amandes", quantitePortion: 30, unite: "g" },
      { ingredientId: "fruits-rouges", quantitePortion: 80, unite: "g" },
      { ingredientId: "yaourt-grec-nature", quantitePortion: 150, unite: "g" },
    ],
  },
  {
    id: "assiette-poulet-riz-lentilles",
    nom: "Assiette poulet, riz & lentilles",
    repas: "Déjeuner",
    assemblage: false,
    portionsReference: 4,
    etapes: "1. Riz. 300 g + eau indiquée dans le cuiseur.\n2. Poulet. Coupe 700 g en morceaux, huile + épices. Air fryer 200°C, 15–18 min, secoue à mi-cuisson.\n3. Légumes. Potiron en dés (400 g), oignon rouge en quartiers, huile + sel. Air fryer 200°C, 15 min ; tomates cerises les 5 dernières min.\n4. Lentilles. Égoutte, rince, assaisonne avec huile, citron, sel.\n5. Boîtes. 1 poing de riz, 1 main de lentilles, poulet, légumes, un quartier de citron. Frigo 3–4 jours.",
    ingredients: [
      { ingredientId: "oignon-rouge", quantitePortion: 0.25, unite: "pièce" },
      { ingredientId: "tomates-cerises", quantitePortion: 62.5, unite: "g" },
      { ingredientId: "poulet-morceaux-filet-cuisse-pilon", quantitePortion: 175, unite: "g" },
      { ingredientId: "paprika", quantitePortion: 0.5, unite: "c. à café" },
      { ingredientId: "poivre", quantitePortion: 0.125, unite: "c. à café" },
      { ingredientId: "huile-d-olive", quantitePortion: 0.75, unite: "c. à soupe" },
      { ingredientId: "ail-en-poudre", quantitePortion: 0.25, unite: "c. à café" },
      { ingredientId: "lentilles", quantitePortion: 200, unite: "g" },
      { ingredientId: "potiron", quantitePortion: 100, unite: "g" },
      { ingredientId: "citron", quantitePortion: 0.25, unite: "pièce" },
      { ingredientId: "cumin", quantitePortion: 0.25, unite: "c. à café" },
      { ingredientId: "riz", quantitePortion: 75, unite: "g" },
      { ingredientId: "sel", quantitePortion: 0.25, unite: "c. à café" },
    ],
  },
  {
    id: "wraps-chili-au-poulet-riz",
    nom: "Wraps chili au poulet & riz",
    repas: "Déjeuner",
    assemblage: false,
    portionsReference: 9,
    etapes: "Un déjeuner tout-en-un : protéine + légumineuses + légumes + féculent. Idéal le dimanche.\n1. Lance le riz. 300–350 g de riz + 2 mugs d'eau dans le cuiseur. Démarre-le et oublie-le.\n2. Oignons. 2–3 c. à soupe d'huile dans la poêle. Coupe 2 oignons en dés, 5 min.\n3. Ail et poivrons. Hache 3 gousses d'ail, coupe 2 poivrons en dés. Ajoute, 5 min.\n4. Poulet. Ajoute 1 kg de poulet haché. Cuis 10–12 min en l'écrasant.\n5. Épices. Cumin, paprika, sel (2 c. à café ½ chacun), chili et poivre (1½ chacun). Remue 1–2 min.\n6. Potiron et tomates. Potiron en petits dés (400–500 g), tomates concassées, concentré de tomate.\n7. Haricots. Égoutte et ajoute 2 boîtes de haricots rouges.\n8. Mijotage. Feu doux, à découvert, 30–35 min, jusqu'à très épais. En parallèle : étale le riz cuit pour qu'il refroidisse.\n9. Épinards. 5 min avant la fin, ajoute 200 g d'épinards.\n10. Refroidissement complet avant de mélanger, sinon les wraps se détrempent.\n11. Mélange chili froid + riz froid.\n12. Montage. Garnis, replie, roule serré.\n13. Emballage. Bien serré, à plat au congélateur (2–3 mois).\nAu quotidien : décongèle dans le sac réfrigéré. Micro-ondes 2–3 min sans le film, ou froid.",
    ingredients: [
      { ingredientId: "poivron", quantitePortion: 0.22, unite: "pièce" },
      { ingredientId: "huile-d-olive", quantitePortion: 0.28, unite: "c. à soupe" },
      { ingredientId: "cumin", quantitePortion: 0.28, unite: "c. à café" },
      { ingredientId: "sel", quantitePortion: 0.28, unite: "c. à café" },
      { ingredientId: "epinards", quantitePortion: 22.2, unite: "g" },
      { ingredientId: "oignon", quantitePortion: 0.22, unite: "pièce" },
      { ingredientId: "poivre", quantitePortion: 0.17, unite: "c. à café" },
      { ingredientId: "riz", quantitePortion: 36.1, unite: "g" },
      { ingredientId: "paprika", quantitePortion: 0.28, unite: "c. à café" },
      { ingredientId: "potiron", quantitePortion: 50, unite: "g" },
      { ingredientId: "tomates-concassees", quantitePortion: 88.9, unite: "g" },
      { ingredientId: "concentre-de-tomate", quantitePortion: 0.22, unite: "c. à soupe" },
      { ingredientId: "ail", quantitePortion: 0.33, unite: "gousse" },
      { ingredientId: "poulet-hache", quantitePortion: 111.1, unite: "g" },
      { ingredientId: "haricots-rouges-ou-noirs", quantitePortion: 88.9, unite: "g" },
      { ingredientId: "chili-ou-piment-doux", quantitePortion: 0.17, unite: "c. à café" },
      { ingredientId: "wraps-complets-ou-pitas", quantitePortion: 1, unite: "pièce" },
    ],
  },
  {
    id: "poulet-marine",
    nom: "Poulet mariné",
    repas: "Dîner",
    assemblage: false,
    portionsReference: 3.5,
    etapes: "1. Marinade. Yaourt, huile, jus de citron, ail écrasé, épices.\n2. Poulet. Entaille légèrement, enrobe, frigo 30 min à 1 nuit.\n3. Cuisson air fryer 200°C : filets 14–16 min · cuisses désossées 16–18 min · pilons 22–25 min · brochettes 12–14 min. Retourne à mi-cuisson.\n4. Contrôle. Jus clair, chair blanche jusqu'au centre.\nService : avec un poing de riz ou de patate douce et des légumes à l'huile d'olive.",
    ingredients: [
      { ingredientId: "huile-d-olive", quantitePortion: 0.57, unite: "c. à soupe" },
      { ingredientId: "poulet-morceaux-filet-cuisse-pilon", quantitePortion: 200, unite: "g" },
      { ingredientId: "ail", quantitePortion: 0.57, unite: "gousse" },
      { ingredientId: "poivre", quantitePortion: 0.14, unite: "c. à café" },
      { ingredientId: "paprika", quantitePortion: 0.29, unite: "c. à café" },
      { ingredientId: "citron", quantitePortion: 0.14, unite: "pièce" },
      { ingredientId: "yaourt-grec-nature", quantitePortion: 0.86, unite: "c. à soupe" },
      { ingredientId: "sel", quantitePortion: 0.29, unite: "c. à café" },
      { ingredientId: "cumin", quantitePortion: 0.29, unite: "c. à café" },
    ],
  },
  {
    id: "bol-yaourt-grec",
    nom: "Bol yaourt grec",
    repas: "Petit-déjeuner",
    assemblage: false,
    portionsReference: 1,
    etapes: "1. Verse 200 g de yaourt grec dans un bol.\n2. Ajoute une grosse poignée de fruits rouges.\n3. Concasse grossièrement une poignée de noix et d'amandes dans ta main et parsème.\n4. Filet de miel si tu veux. Pain au levain à côté si tu as encore faim.\nAstuce : des fruits rouges surgelés, mis au frigo la veille, sont décongelés le matin.",
    ingredients: [
      { ingredientId: "miel", quantitePortion: 1, unite: "c. à café" },
      { ingredientId: "yaourt-grec-nature", quantitePortion: 200, unite: "g" },
      { ingredientId: "fruits-rouges", quantitePortion: 80, unite: "g" },
      { ingredientId: "noix-et-amandes", quantitePortion: 30, unite: "g" },
    ],
  },
  {
    id: "poisson-gras-orge-legumes-verts",
    nom: "Poisson gras, orge & légumes verts",
    repas: "Dîner",
    assemblage: false,
    portionsReference: 1,
    etapes: "1. Orge (à l'avance). 1 volume d'orge pour 3 d'eau au cuiseur à riz. Fais-en pour 3 jours, frigo.\n2. Saumon. Huile, sel, poivre. Air fryer 180–200°C, 10–12 min.\n3. Légumes. Ail 1 min, épinards ou blettes 2–3 min.\n4. Réchauffe un poing d'orge, jus de citron.\nVersion express : une boîte de sardines ou de maquereau à la place du pavé.",
    ingredients: [
      { ingredientId: "pave-de-saumon", quantitePortion: 150, unite: "g" },
      { ingredientId: "huile-d-olive", quantitePortion: 1, unite: "c. à soupe" },
      { ingredientId: "epinards", quantitePortion: 60, unite: "g" },
      { ingredientId: "ail", quantitePortion: 1, unite: "gousse" },
      { ingredientId: "citron", quantitePortion: 0.5, unite: "pièce" },
      { ingredientId: "orge-perle", quantitePortion: 60, unite: "g" },
    ],
  },
  {
    id: "bowl-poisson-gras-pois-chiches",
    nom: "Bowl poisson gras & pois chiches",
    repas: "Déjeuner",
    assemblage: false,
    portionsReference: 1,
    etapes: "⚠️ Pas de féculent inclus — ajouter un poing de riz ou de pain pour un repas complet.\n1. Égoutte ½ boîte de pois chiches.\n2. Épinards/roquette + riz dans la boîte.\n3. Concombre et tomate en dés.\n4. Émiette le poisson par-dessus. Huile, citron, sel, poivre.\nAvec un pavé de saumon : air fryer 180°C, 10–12 min, la veille.",
    ingredients: [
      { ingredientId: "pois-chiches", quantitePortion: 200, unite: "g" },
      { ingredientId: "concombre", quantitePortion: 0.5, unite: "pièce" },
      { ingredientId: "epinards", quantitePortion: 30, unite: "g" },
      { ingredientId: "tomates", quantitePortion: 1, unite: "pièce" },
      { ingredientId: "huile-d-olive", quantitePortion: 1, unite: "c. à soupe" },
      { ingredientId: "citron", quantitePortion: 0.5, unite: "pièce" },
      { ingredientId: "riz", quantitePortion: 60, unite: "g" },
      { ingredientId: "poisson-en-boite-thon-sardines-maquereau", quantitePortion: 117.5, unite: "g" },
    ],
  },
  {
    id: "riz-mexicain-au-poulet",
    nom: "Riz mexicain au poulet",
    repas: "Déjeuner",
    assemblage: false,
    portionsReference: 4,
    etapes: "1. Oignon. Huile dans la poêle, oignon en dés, 4 min.\n2. Poulet. En dés, 6–7 min.\n3. Ail et poivron. Ajoute, 3 min.\n4. Épices et riz. Ajoute les épices, puis le riz rincé, 1 min.\n5. Liquide. Tomates + bouillon. Frémissement, couvre, feu doux, 18–20 min sans ouvrir.\n6. Haricots. Ajoute, couvre 5 min.\n7. Finition. Jus de citron vert. 4 boîtes, frigo 3–4 jours.",
    ingredients: [
      { ingredientId: "oignon", quantitePortion: 0.25, unite: "pièce" },
      { ingredientId: "haricots-rouges-ou-noirs", quantitePortion: 100, unite: "g" },
      { ingredientId: "citron-vert", quantitePortion: 0.25, unite: "pièce" },
      { ingredientId: "poulet-morceaux-filet-cuisse-pilon", quantitePortion: 150, unite: "g" },
      { ingredientId: "tomates-concassees", quantitePortion: 100, unite: "g" },
      { ingredientId: "riz", quantitePortion: 62.5, unite: "g" },
      { ingredientId: "bouillon-de-volaille-halal", quantitePortion: 0.25, unite: "cube" },
      { ingredientId: "sel", quantitePortion: 0.25, unite: "c. à café" },
      { ingredientId: "chili-ou-piment-doux", quantitePortion: 0.25, unite: "c. à café" },
      { ingredientId: "cumin", quantitePortion: 0.5, unite: "c. à café" },
      { ingredientId: "ail", quantitePortion: 0.5, unite: "gousse" },
      { ingredientId: "huile-d-olive", quantitePortion: 0.5, unite: "c. à soupe" },
      { ingredientId: "poivron", quantitePortion: 0.25, unite: "pièce" },
      { ingredientId: "paprika", quantitePortion: 0.5, unite: "c. à café" },
    ],
  },
  {
    id: "tajine-de-kefta-a-la-poele",
    nom: "Tajine de kefta à la poêle",
    repas: "Dîner",
    assemblage: false,
    portionsReference: 2.5,
    etapes: "1. Boulettes. Oignon râpé, herbes ciselées, viande, cumin, sel. Boulettes taille noix.\n2. Sauce. Huile, 2e oignon 4 min, ail 1 min, tomates + épices 5 min.\n3. Mijotage. Boulettes dans la sauce, couvre, feu doux, 15 min, retourne à mi-cuisson.\n4. Œufs. Casse 3 œufs entre les boulettes, couvre 5–6 min.\n5. Herbes restantes, pain au levain.",
    ingredients: [
      { ingredientId: "ail", quantitePortion: 0.8, unite: "gousse" },
      { ingredientId: "poivre", quantitePortion: 0.2, unite: "c. à café" },
      { ingredientId: "paprika", quantitePortion: 0.4, unite: "c. à café" },
      { ingredientId: "oignon", quantitePortion: 0.8, unite: "pièce" },
      { ingredientId: "tomates-concassees", quantitePortion: 160, unite: "g" },
      { ingredientId: "persil-ou-coriandre", quantitePortion: 0.2, unite: "bouquet" },
      { ingredientId: "huile-d-olive", quantitePortion: 0.4, unite: "c. à soupe" },
      { ingredientId: "cumin", quantitePortion: 0.4, unite: "c. à café" },
      { ingredientId: "pain-complet-au-levain", quantitePortion: 1, unite: "tranche" },
      { ingredientId: "sel", quantitePortion: 0.4, unite: "c. à café" },
      { ingredientId: "boeuf-ou-agneau-hache", quantitePortion: 200, unite: "g" },
      { ingredientId: "oeufs", quantitePortion: 1.2, unite: "pièce" },
    ],
  },
  {
    id: "snack-sunnah-dattes-banane-pouch",
    nom: "Snack Sunnah : dattes, banane & pouch",
    repas: "Snack",
    assemblage: true,
    portionsReference: 1,
    etapes: "Carburant avant la séance, 45–60 min avant.\n- 2–3 dattes\n- 1 banane\n- 1 pouch de skyr",
    ingredients: [
      { ingredientId: "pouch-skyr-15-g-de-proteines", quantitePortion: 1, unite: "pièce" },
      { ingredientId: "banane", quantitePortion: 1, unite: "pièce" },
      { ingredientId: "dattes", quantitePortion: 3, unite: "pièce" },
    ],
  },
  {
    id: "wrap-kefta-houmous",
    nom: "Wrap kefta & houmous",
    repas: "Déjeuner",
    assemblage: false,
    portionsReference: 4,
    etapes: "1. Keftas. Oignon râpé, persil ciselé, viande, épices. 12 petits boudins.\n2. Cuisson. Air fryer 200°C, 10–12 min (ou poêle 8–10 min).\n3. Garniture. Tomates en rondelles, oignon rouge en lamelles.\n4. Montage. Houmous, salade, tomate, oignon, 3 keftas. Roule.\nPour le chantier : keftas en boîte, garniture à part, montage au moment de manger.",
    ingredients: [
      { ingredientId: "houmous", quantitePortion: 50, unite: "g" },
      { ingredientId: "boeuf-ou-agneau-hache", quantitePortion: 125, unite: "g" },
      { ingredientId: "paprika", quantitePortion: 0.25, unite: "c. à café" },
      { ingredientId: "wraps-complets-ou-pitas", quantitePortion: 1, unite: "pièce" },
      { ingredientId: "tomates", quantitePortion: 0.5, unite: "pièce" },
      { ingredientId: "sel", quantitePortion: 0.25, unite: "c. à café" },
      { ingredientId: "salade", quantitePortion: 1, unite: "poignée" },
      { ingredientId: "oignon", quantitePortion: 0.25, unite: "pièce" },
      { ingredientId: "cumin", quantitePortion: 0.25, unite: "c. à café" },
      { ingredientId: "persil-ou-coriandre", quantitePortion: 0.125, unite: "bouquet" },
      { ingredientId: "oignon-rouge", quantitePortion: 0.125, unite: "pièce" },
      { ingredientId: "poivre", quantitePortion: 0.125, unite: "c. à café" },
    ],
  },
  {
    id: "avoine-trempee-oeufs-brouilles",
    nom: "Avoine trempée & œufs brouillés",
    repas: "Petit-déjeuner",
    assemblage: false,
    portionsReference: 1,
    etapes: "1. La veille. Dans un pot, mélange 50 g de flocons d'avoine, 150 ml de lait ou de kéfir, 2 c. à soupe de yaourt grec et 1 c. à soupe de chia. Ferme, frigo.\n2. Le matin. Bats 2–3 œufs avec une pincée de sel. Poêle, 1 c. à café d'huile, feu doux, remue 2–3 min.\n3. Ajoute une poignée de fruits rouges sur l'avoine. Miel facultatif.",
    ingredients: [
      { ingredientId: "yaourt-grec-nature", quantitePortion: 2, unite: "c. à soupe" },
      { ingredientId: "flocons-d-avoine", quantitePortion: 50, unite: "g" },
      { ingredientId: "oeufs", quantitePortion: 2.5, unite: "pièce" },
      { ingredientId: "fruits-rouges", quantitePortion: 80, unite: "g" },
      { ingredientId: "graines-de-chia", quantitePortion: 1, unite: "c. à soupe" },
      { ingredientId: "lait-ou-kefir", quantitePortion: 150, unite: "ml" },
    ],
  },
  {
    id: "petit-dej-habituel-3-oeufs-12-avocat",
    nom: "Petit-déj habituel : 3 œufs & ½ avocat",
    repas: "Petit-déjeuner",
    assemblage: false,
    portionsReference: 1,
    etapes: "Mon petit-déjeuner de tous les jours.\n1. Poêle, 1 c. à café d'huile d'olive, feu moyen. Casse 3 œufs : au plat (couvert, 3–4 min) ou brouillés (2–3 min en remuant).\n2. Coupe l'avocat, garde la moitié avec le noyau au frigo, tranche l'autre.\n3. Sel, poivre. Fruits en plus si tu as envie.",
    ingredients: [
      { ingredientId: "oeufs", quantitePortion: 3, unite: "pièce" },
      { ingredientId: "huile-d-olive", quantitePortion: 1, unite: "c. à café" },
      { ingredientId: "avocat", quantitePortion: 0.5, unite: "pièce" },
    ],
  },
  {
    id: "boeuf-marine",
    nom: "Bœuf mariné",
    repas: "Dîner",
    assemblage: false,
    portionsReference: 1.5,
    etapes: "1. Sors la viande 15 min avant. Frotte avec huile, ail écrasé, épices, citron.\n2. Faux-filet : poêle très chaude, 2–4 min par face. Repos 5 min avant de couper.\n3. Brochettes : air fryer 200°C, 8–10 min.\nRepère : viande rouge avec modération, comme dans les zones bleues.",
    ingredients: [
      { ingredientId: "huile-d-olive", quantitePortion: 0.67, unite: "c. à soupe" },
      { ingredientId: "paprika", quantitePortion: 0.33, unite: "c. à café" },
      { ingredientId: "sel", quantitePortion: 1, unite: "g" },
      { ingredientId: "boeuf-faux-filet-ou-cubes", quantitePortion: 200, unite: "g" },
      { ingredientId: "ail", quantitePortion: 0.67, unite: "gousse" },
      { ingredientId: "citron", quantitePortion: 0.1, unite: "pièce" },
      { ingredientId: "cumin", quantitePortion: 0.33, unite: "c. à café" },
    ],
  },
];

